define(
  {
    ui: {
      nl: {
        meta: {
          name: 'nl',
          label: 'Nederlands'
        },
        login: {
          header: 'Inloggen',
          placeholder_username: 'Vul uw gebruikersnaam in',
          placeholder_password: 'Vul uw wachtwoord in',
          label_rememberMe: 'Onthoud mij',
          button_login: 'Inloggen',
          button_loggingIn: 'Inloggen...',
          forgot_password: 'Wachtwoord vergeten?',
          forgetPassword: 'Wachtwoord vergeten',
          emailAddress: 'Emailadres',
          resetPassword: 'Wachtwoord opnieuw instellen',
          returnLogin: 'Terugkeren om in te loggen',
          changePassword: 'Wachtwoord wijzigen',
          downloadApp: 'Download mobiele app',
          ph_username: 'Gebruikersnaam',
          ph_password: 'Wachtwoord',
          ph_newPass: 'nieuw wachtwoord',
          ph_retypePass: 'Herhaal wachtwoord',
          alert_fillfiled: 'Vul alle velden in!',
          alert_wrongUserPass: 'Onjuiste gebruikersnaam of wachtwoord!',
          loading_User: 'Gebruikersinformatie laden...',
          loading_Message: 'Berichten laden...',
          loading_Group: 'Groepen laden...',
          loading_Members: 'Teamleden laden...',
          loading_everything: 'Alles is geladen!',
          logout: 'Uitloggen',
          loading: 'Laden..',
          loading_clientGroups: 'Cliëntengroepen laden...',
          loading_clients: 'Clienten laden',
          loading_teams: 'Teams laden...',
          loading_tasks: 'Taken laden...'
        },
        dashboard: {
          thisWeek: 'Deze week',
          welcome: 'Welkom',
          everyone: 'Iedereen',
          newMessage: 'Nieuwe berichten',
          goToInbox: 'Ga naar inbox',
          loadingPie: 'Cirkeldiagrammen laden...',
          possiblyReachable: 'Mogelijk bereikbaar',
          noPlanning: 'Geen Planning',
          load: 'laden...',
          time: {
            days: 'd',
            hours: 'u',
            minutes: 'm',
            seconds: 's'
          },
          announcements: 'Alarmberichten',
          loadingP2000: 'Alarmberichten laden...',
          noP2000: 'Er zijn geen alarmberichten.',
          accessibilityStatement: 'Overzicht bereikbaarheid',
          loading: 'aan het laden...',
          accessible: 'bereikbaar'
        },
        agenda: {
          requiredPeople: 'Benodigd',
          newAvail: 'Nieuwe bereikbaarheid',
          day: 'Dag',
          week: 'Week',
          month: 'Maand',
          updateAvail: 'Update bereikbaarheid',
          from: 'Vanaf',
          till: 'Tot',
          state: 'Status',
          selectAState: 'Selecteer een status',
          reoccuring: 'Elke week',
          lessPeople: 'Er zijn $v mensen te weinig als nodig.',
          samePeople: 'Er zijn net zoveel mensen als nodig.',
          morePeople: 'Er zijn $v mensen meer als nodig.',
          wished: 'Behoefte',
          combine_reoccuring: 'Dit is een gecombineerde planning rij met opeenvolgende rijen.',
          sendMsgToMember: 'Send Message To Members',
          add: 'Toevoegen',
          del: 'Verwijderen',
          change: 'Wijzigen',
          setWish: 'Behoefte opslaan',
          timeline: 'Tijdlijn',
          statistics: 'Statistics',
          barCharts: 'Staafdiagrammen',
          wishes: 'Behoefte',
          legenda: 'Legenda',
          group: 'Team',
          groups: 'Team',
          members: 'Leden',
          teamMembers: 'Teamleden',
          bothAvailable: 'Both available',
          northAavailable: 'available North',
          southAvailable: 'available South',
          skipperOutService: 'Skipper Of Service',
          notAvailable: 'Niet bereikbaar', // Niet Beschikbaar
          notachieve: 'Niet gearchieveerd',
          legendaLabels: {
            morePeople: 'Genoeg Mensen',
            enoughPeople: 'Precies genoeg mensen',
            lessPeople: 'Te weinig mensen'
          },
          lastSyncTime: 'Laatste synchronisatie tijd:',
          dataRangeStart: 'Datumbereik start: ',
          DataRangeEnd: 'Datumbereik eind: ',
          loadingTimeline: 'Tijdlijn laden...',
          addTimeSlot: 'Tijdslot toevoegen...',
          slotAdded: 'Nieuw tijdslot is succesvol toegevoegd',
          changingSlot: 'Tijdslot wijzigen...',
          slotChanged: 'Tijdslot succesvol gewijzigd.',
          changingWish: 'Behofte wordt veranderd...',
          wishChanged: 'De behoefte is succesvol gewijzigd.',
          deletingTimeslot: 'Tijdslot verwijderen...',
          timeslotDeleted: 'Tijdslot is succesvol verwijderd.',
          refreshTimeline: 'Tijdlijn refreshen...',
          preCompilingStortageMessage: 'Voor gecompileert kort bericht',
          weeklyPlanning: 'Weekelijkse planninng',
          planning: 'Mijn planning',
          planningOf: 'Planning van ',
          minNumber: 'Minimum aantal benodigden',
          statDays: 'dagen',
          statHours: 'uren',
          statMinutes: 'minuten',
          statPeopleLess: 'Less people than expected',
          statPeopleEven: 'Precies genoeg mensen',
          statPeopleMore: 'Meer mensen dan verwacht',
          getWishes: 'Pak de minimale benodigde waarde...',
          daterangerToday: 'Vandaag',
          daterangerTomorrow: 'Morgen',
          daterangerYesterday: 'Gisteren',
          daterangerNext3Days: 'Volgende 3 dagen',
          daterangerNext7Days: 'Volgende 7 dagen',
          rangeInfoTotalSelectedDays: 'Totaal geselecteerde dagen: ',
          rangeInfoTime: 'Tijd: ',
          rangeInfoWeekNumber: 'Weeknummer: ',
          rangeInfoMonth: 'Maand: ',
          rangeInfoTotalDays: ', Totaal aantal dagen: ',
          query: 'Er zijn wat problemen met het synchroniseren van de agenda. Kunt u alstublieft uw browser verversen om de laatste informatie op te halen.',
          pastAdding: 'Het is niet mogelijk in het verleden te plannen!',
          errorAdd: 'Error with adding a new planning!',
          errorChange: 'Error with changing planning!',
          pastChanging: 'Het wijzigen van een planning in het verleden is niet mogelijk!',
          pastDeleting: 'Het verwijderen van een planning in het verleden is niet mogelijk!',
          remove: 'Fout(en) met het verwijderen van de planning!',
          wisher: 'Fout(en) met het wijzigen van de behoefte',
          editTimeline: 'Wijzig de tijdlijn van ',
          notAuth: 'Het is niet mogelijk om iemands anders planning te wijzigen, behalve als de rol van coordinator. Als coordinator kan je de planning van andere wijzigen  door op hun naam te klikken in de lijst. Je wordt naar een andere pagina genavigeerd waar de planning van het betreffende lid is te wijzigen.'
        },
        planboard: {
          planboard: 'Agenda',
          newAvail: 'Nieuwe bereikbaarheid',
          day: 'Dag',
          week: 'Week',
          month: 'Maand',
          updateAvail: 'Update bereikbaarheid',
          from: 'Van',
          till: 'Tot',
          state: 'Status',
          selectAState: 'selecteer een status',
          reoccuring: 'Herhaling',
          lessPeople: 'Er is een tekort van $v mens(en)!',
          samePeople: 'Er zijn precies genoeg mensen.',
          morePeople: 'Er is een overschot van $v mens(en)!',
          wished: 'Gewenst',
          combine_reoccuring: 'Dit is een gecombineerde planning.',
          sendMsgToMember: 'Stuur bericht naar leden',
          add: 'Toevoegen',
          del: 'Verwijderen',
          change: 'Wijzigen',
          setWish: 'Behoefte instellen',
          timeline: 'Tijdlijn',
          statistics: 'Statistieken',
          barCharts: 'Staafdiagrammen',
          wishes: 'Behoefte',
          legenda: 'Legenda',
          group: 'Groep',
          groups: 'Groepen',
          members: 'Leden',
          teamMembers: 'Teamleden',
          bothAvailable: 'Beide bereikbaar',
          northAavailable: 'Beschikbaar Noord',
          southAvailable: 'Beschikbaar Zuid',
          skipperOutService: 'Schipper van dienst',
          notAvailable: 'Niet bereikbaar',
          notachieve: 'Niet behaald',
          legendaLabels: {
            morePeople: 'Meer mensen',
            enoughPeople: 'Precies genoeg mensen',
            lessPeople: 'Te weinig mensen'
          },
          lastSyncTime: 'Laatste synchronisatietijd:',
          dataRangeStart: 'Begin gegevensscala: ',
          DataRangeEnd: 'Eind gegevensscala: ',
          daterangerToday: 'Vandaag',
          daterangerTomorrow: 'Morgen',
          daterangerLast7Days: 'Laatste 7 dagen',
          daterangerYesterday: 'Gisteren',
          daterangerNext3Days: 'Volgende 3 dagen',
          daterangerNext7Days: 'Volgende 7 dagen',
          loadingTimeline: 'Tijdlijn laden...',
          rangeInfoTotalSelectedDays: 'Totaal aantal geselecteerde dagen: ',
          rangeInfoTime: 'Tijd: ',
          rangeInfoWeekNumber: 'Weeknummer: ',
          rangeInfoMonth: 'Maand: ',
          rangeInfoTotalDays: ', Totaal aantal dagen: ',
          addTimeSlot: 'Tijdslot toevoegen...',
          slotAdded: 'Tijdslot succesvol toegevoegd.',
          changingSlot: 'Tijdslot wijzigen...',
          slotChanged: 'Tijdslot succesvol gewijzigd.',
          changingWish: 'Behoefte wijzigen...',
          wishChanged: 'Behoefte succesvol gewijzigd.',
          deletingTimeslot: 'Tijdslot verwijderen...',
          timeslotDeleted: 'Tijdslot succesvol verwijderd.',
          refreshTimeline: 'Tijdlijn vernieuwen...',
          preCompilingStortageMessage: 'Opstellen tekortbericht',
          weeklyPlanning: 'Mijn wekelijkse planning',
          weeklyPlanningOf: 'Wekelijkse planning van ',
          planning: 'Mijn planning',
          planningOf: 'Planning van ',
          minNumber: 'Minimum aantal benodigde mensen',
          time: 'Time: ',
          weekNumber: 'Weeknummer: ',
          monthNumber: 'Maand nummer: ',
          totalDays: 'Totaal dagen: ',
          removeTasksRange: function(options)
          {
            if(! _.isUndefined(options))
            {
              var html = 'Weet u zeker dat u de taken van ' + options.range.start + ' t/m ' + options.range.end;
              html += ' van ' + options.group + ' ' + options.name;
              html += ' wilt verwijderen?';
            }

            return html;
          },
          tasksDeleted: function(options)
          {
            if(! _.isUndefined(options))
            {
              var html = 'De taken van ' + options.range.start + ' t/m ' + options.range.end;
              html += ' van ' + options.group + ' ' + options.name;
              html += ' zijn verwijderd.';
            }

            return html;
          },
          noTasksFounded: 'Geen taken gevonden in de opegegeven range.',
          removeTasksTitle: 'Verwijderen taken'
        },
        message: {
          messages: 'Berichten',
          composeAMessage: 'Bericht opstellen',
          compose: 'Opstellen',
          inbox: 'Inbox',
          outbox: 'Outbox',
          trash: 'Prullenbak',
          composeMessage: 'Bericht opstellen',
          close: 'Sluiten',
          broadcast: 'Extra medium',
          sms: 'SMS',
          email: 'Email',
          receviers: 'Ontvanger(s)',
          webTRCWebLink: 'Een video conferentie is geopend doe mee!',
          // troubled
          // chooseRecept: 'Ontvanger(s) selecteren',
          //
          subject: 'Onderwerp',
          message: 'Bericht',
          sendMessage: 'Bericht versturen',
          sender: 'Zender',
          date: 'Datum',
          questionText: 'Bericht',
          reply: 'Antwoorden',
          del: 'Verwijderen',
          noMessage: 'Er zijn geen berichten.',
          from: 'Van',
          newMsg: 'Nieuw',
          deleteSelected: 'Verwijder geselecteerde berichten',
          someMessage: 'Er zijn $v berichten',
          emptyTrash: 'Prullenbak legen',
          noMsgInTrash: 'Er zijn geen berichten.',
          box: 'Box',
          persons: 'Personen',
          restoreSelected: 'Geselecteerde berichten terugplaatsen',
          loadingMessage: 'Bericht laden...',
          escalation: 'Escalatiebericht',
          reportMessage: 'Nieuw rapport van',
          escalationBody: function (diff, startDate, startTime, endDate, endTime)
          {
            return 'Er is een tekort van ' +
              diff +
              ' mensen tussen ' +
              startDate + ' ' +
              startTime + ' en ' +
              endDate + ' ' +
              endTime + '. ' +
              'Zet uzelf a.u.b. op bereikbaar indien u bereikbaar bent voor die periode';
          },
          removed: 'Bericht succesvol verwijderd.',
          removing: 'Bericht verwijderen...',
          refreshing: 'Bericht vernieuwen...',
          removingSelected: 'Geselecteerde berichten verwijderen...',
          restoring: 'Bericht terugplaatsen...',
          restored: 'Bericht succesvol teruggeplaatst.',
          restoringSelected: 'Geselecteerde berichten terugplaatsen...',
          emptying: 'Prullenbak leegmaken...',
          emptied: 'Prullenbak succesvol geleegd.',
          sending: 'Bericht versturen...',
          sent: 'Bericht verstuurd.',
          typeSubject: 'Vul een onderwerp in.',
          // messages: 'Berichten',
          ph_filterMessage: 'Berichten filteren...',
          noReceivers: 'Selecteer een ontvanger',
          emptyMessageBody: 'Het bericht is leeg, typ a.u.b. een bericht.',
          send: 'Versturen'
        },
        groups: {
          groups: 'Groepen',
          newGroup: 'Nieuwe groep',
          newMember: 'Nieuw teamlid',
          serach: 'Zoeken',
          addNewGroup: 'Nieuwe groep toevoegen',
          editGroup: 'Groep wijzigen',
          searchResults: 'Zoekresultaten',
          group: 'Groep',
          close: 'Sluiten',
          name: 'Naam',
          saveGroup: 'Groep opslaan',
          registerMember: 'Lid registreren',
          role: 'Functie',
          selectRole: 'Selecteer een functie',
          // troubled
          // selectGroup: 'Selecteer een group',
          //
          email: 'Email',
          phone: 'Telefoon',
          address: 'Adres',
          postCode: 'Postcode',
          tel: 'Telefoonnummer',
          city: 'Woonplaats',
          userName: 'Gebruikersnaam',
          password: 'Wachtwoord',
          saveMember: 'Lid opslaan',
          serachFor: 'Zoekresultaten voor ',
          sorryCanNotFind: 'Sorry, geen resultaten.',
          addToGroup: 'Aan groep toevoegen',
          addMemberToGroup: 'Voeg geselecteerde leden aan groep toe',
          resultCount: 'Er zijn $v resultaten.',
          deleteGroup: 'Groep verwijderen',
          noMembers: 'Er zijn geen leden.',
          removeSelectedMembers: 'Geselecteerde leden verwijderen',
          memberCount: 'Er zijn $v leden.',
          searchingMembers: 'Teamleden zoeken...',
          addingNewMember: 'Nieuw lid toevoegen...',
          memberAdded: 'Lid succesvol aan groep toegevoegd.',
          refreshingGroupMember: 'Groepen- en ledenlijst vernieuwen...',
          removingMember: 'Lid uit groep verwijderen...',
          memberRemoved: 'Lid succesvol uit groep verwijderd.',
          removingSelected: 'Geselecteerde leden verwijderen...',
          saving: 'Groep opslaan...',
          groupSaved: 'Groep succesvol opgeslagen.',
          registerNew: 'Nieuw lid registreren...',
          memberRegstered: 'Lid succesvol geregistreerd.',
          deleting: 'Groep verwijderen...',
          deleted: 'Groep succesvol verwijderd.',
          filterMembers: 'Teamleden filteren...',
          searchfor: 'voornaam, achternaam..'
        },
        profile: {
          profile: 'Profiel',
          edit: 'Wijzigen',
          password: 'Wachtwoord',
          timeline: 'Tijdlijn',
          profileView: 'Profiel weergave',
          userGroups: 'Gebruikersgroepen',
          role: 'Functie',
          email: 'Email',
          phone: 'Telefoon',
          address: 'Adres',
          postcode: 'Postcode',
          city: 'Woonplaats',
          editProfile: 'Profiel wijzigen',
          name: 'Naam',
          saveProfile: 'Profiel opslaan',
          passChange: 'Wachtwoord wijzigen',
          currentPass: 'Huidig wachtwoord',
          newPass: 'Nieuw wachtwoord',
          newPassRepeat: 'Herhaal nieuw wachtwoord',
          changePass: 'Wachtwoord wijzigen',
          newAvail: 'Nieuwe bereikbaarheid',
          userName: 'Gebruikersnaam',
          pincode: 'teamlidcode',
          // saveProfile: 'Profielinformatie opslaan...',
          refreshing: 'Profielinformatie vernieuwen...',
          dataChanged: 'Profielgegevens succesvol gewijzigd.',
          pleaseFill: 'Vul a.u.b. alle velden in!',
          passNotMatch: 'Ingevoerd wachtwoord komt niet overeen. Probeer het opnieuw.',
          changingPass: 'Wachtwoord wijzigen...',
          passChanged: 'Wachtwoord succesvol gewijzigd.',
          passwrong: 'Ingevoerd wachtwoord is foutief! Probeer het opnieuw.',
          currentPassWrong: 'Het ingevulde oude wachtwoord komt niet overeen met het huidige! Probeer opnieuw.',
          newTimeslotAdded: 'Nieuw tijdslot succesvol toegevoegd.',
          changingTimeslot: 'Tijdslot wijzigen...',
          timeslotChanged: 'Tijdslot succesvol gewijzigd.',
          exampleBirthDate: 'Bijvoorbeeld: 01-01-2001',
          firstName: 'Voornaam',
          lastName: 'Achternaam',
          editProfileImg: 'Profielfoto wijzigen',
          profileImgSuccessfullyUploaded: 'De profielfoto is succesvol geüpload.',
          loadUploadURL: 'Foto upload URL laden',
          click2upload: 'Klik hier om te uploaden',
          birthday: 'Geboortedatum',
          username: 'Gebruikersnaam',
          retypePassword: 'Herhaal wachtwoord',
          roleChangePrompt: 'Je verandert je eigen rol. Het systeem zal hierdoor automatisch uitloggen. Druk op "Ok" om verder te gaan.',//'You changed your own role, system will automatically logout, press "Yes" to continue.',
          specifyTeam: 'Selecteer een team voor deze gebruiker.',//'You need to sepcify a team to this user'
          authorInfo: 'Auteurinfo laden...',
          changePassWord: 'Wachtwoord wijzigen',
          safePassword: 'Wachtwoord opslaan',
          oldPassword: 'Oud wachtwoord',
          pincode: 'Teamlidcode',
          pincodeInUse: 'Deze teamlidcode is in gebruik. Kies een andere.',
          pincodeNotValid: 'Vul a.u.b. een geldige teamlidcode van maximaal 8 cijfers in!',
          pincodeCorrect: 'Deze teamlidcode is in gebruik of niet geldig! Vul a.u.b. een geldige teamlidcode.',
          pincodeInfo: 'Bovenstaande code kunt u telefonisch gebruiken om u aan te melden als TeamTelefoon uw nummer niet herkent.',
          duplicateNumber: 'Nummer bestaat al. Andere nummer invoeren aub.',
          pincodeInfoPhone: 'De laatste vier cijfers van dit telefoonnummer worden gebruikt voor de teamlidcode, tenzij deze zelf wordt opgegeven.'
        },
        settings: {
          settings: 'Instellingen',
          user: 'Gebruiker',
          application: 'Applicatie',
          userSettings: 'Gebruikersinstellingen',
          appSettings: 'Applicatie-instellingen',
          saveSettings: 'Instellingen opslaan',
          langSetting: 'Taal',
          saving: 'Instellingen wijzigen...',
          refreshing: 'Instellingen vernieuwen...',
          saved: 'Instellingen succesvol gewijzigd.'
        },
        help: {
          header: 'Hulp & Ondersteuning',
          support: 'Ondersteuning'
        },
        downloads: {
          app: 'Binnenkort te downloaden.',
          manual: 'Download handleiding'
        },
        loading: {
          general: 'Laden',
          dashboard: 'dashboard',
          planboard: 'agenda',
          messages: 'berichten',
          teams: 'teams',
          profile: 'profiel',
          settings: 'instellingen'
        },
        teamup: {
          teams: 'Teams',
          selectTeam: 'Selecteer team',
          clients: 'Cliënten',
          selectClientGroup: 'Selecteer een cliëntgroep',
          manage: 'Beheren',
          chooseTeam: 'Selecteer een team',
          edit: 'Bewerk',
          editTeam: 'Bewerk team',
          team: 'Team',
          del: 'Verwijder',
          noMembers: 'Geen leden in dit team.',
          newTeam: 'Nieuw Team',
          teamName: 'Teamnaam',
          createTeam: 'Opslaan',
          newMember: 'Nieuw teamlid',
          name: 'Naam',
          role: 'Rol',
          phone: 'Telefoon',
          street: 'Straat',
          postCode: 'Postcode',
          city: 'Woonplaats',
          email: 'E-mail',
          saveMember: 'Opslaan',
          state: 'Status',
          states: 'Status',
          saveTeam: 'Team opslaan',
          save: 'Opslaan',
          refreshing: 'Teaminformatie opnieuw ophalen',
          dataChanged: 'Data is veranderd.',
          teamSubmitError: 'Fouten tijdens het aanmaken: ',
          queryTeamError: 'Fouten tijdens het opzoeken van de teams.',
          teamNamePrompt1: 'Vul een teamnaam in.',
          teamNamePrompt2: 'Voeg contactdata toe a.u.b.',
          cancel: 'Annuleren',
          chooseRole: 'Kies een rol',
          func: 'Functie',
          chooseFunction: 'Kies een functie',
          newClientGroup: 'Nieuwe groep',
          newClient: 'Nieuwe cliënt',
          reports: 'Rapporten',
          report: 'Rapport',
          noClients: 'Geen cliënten in deze groep',
          TeamClients: 'TEAMS - CLIËNTEN',
          createClientGroup: 'Opslaan',
          contacts: 'Contacten',
          Number: 'Nummer',
          clientProfileUrl: 'URL Cliëntenprofiel',
          addContact: 'Contactpersoon toevoegen',
          editContact: 'Contactpersoon wijzigen',
          saveClient: 'Opslaan',
          group: 'Groep',
          errorSaveClientGroup: 'Opslaan wijzigingen cliëntengroep mislukt.',
          noContacts: 'Er zijn geen contactpersonen gedefinieerd.',
          noReports: 'Er zijn geen rapporten voor deze cliënt.',
          contactCount: 'Er zijn $v contactpersonen.',
          reportCount: 'Er zijn $v rapporten.',
          accountInfoFill: 'Vul uw accountinformatie in a.u.b.',
          passNotSame: 'Wachtwoorden zijn niet hetzelfde.',
          savingMember: 'Lid aan het opslaan...',
          selectTeam: 'Selecteer een team',
          clinetInfoFill: 'Vul de cliëntinformatie (naam en telefoon) in a.u.b.',
          savingClient: 'Cliënt aan het opslaan...',
          clientSubmitError: 'Fouten bij het aanmaken van een nieuwe cliënt.',
          clientGroups: 'Cliëntengroepen',
          teams_Cap: 'Teams',
          editClient: 'Bewerk cliënt',
          loadingNumber: 'Teamtelefoonnummer aan het laden...',
          birthdayError: 'Fout in de geboortedatum.',
          map: 'kaart',
          saveContacts: 'Contactpersonen opslaan',
          loadingReports: 'Rapporten laden',
          reportEmpty: 'Voer een valide titel en beschrijving in!',
          reportValid: 'De invoervelden zijn niet valide!',
          reportBody: 'Beschrijving',
          reportBodyRequired: 'Vul een beschrijving in!',
          reportTitleRequired: 'Vul een titel in!',
          reportBodyMinChars: 'De beschrijving moet uit minimaal 8 karakters bestaan!',
          reportTitleMinChars: 'De beschrijving moet uit minimaal 4 karakters bestaan!',
          reportBodyMaxChars: 'De beschrijving mag maximaal 150 karakters bestaan!',
          reportTitleMaxChars: 'De titel kan uit maximaal 30 karakters bestaan!',
          checkLocalStorage: 'In deze webbrowser is de privé-modus ingeschakeld. Dit wordt niet ondersteund. Hier vindt u informatie over hoe u de privé-modus kunt uitschakelen:',
          readMore: 'Lees meer',
          date: 'Datum',
          datetime: 'Datum en tijd',
          writenBy: 'Geschreven door',
          noSharedStates: 'Geen gedeelde status',
          savingContacts: 'Contactpersonen oplsaan',
          // delClientGroupConfirm: 'Weet u zeker dat u deze cliëntengroep wilt verwijderen? Het kan even duren.',
          // delTeamConfirm: 'Weet u zeker dat u dit team wilt verwijderen? Het kan even duren.',
          deletingClientGroup: 'Groep verwijderen... ',
          from: 'Van',
          to: 'Tot',
          time: 'Tijd',
          duration: 'Duur',
          coordinatorNoTeam: 'Het lijkt erop dat je niet in een team zit. Wijs jezelf toe aan een team.',
          teamMemberNoTeam: 'Het lijkt erop dat je niet in een team zit. Neem contact op met een coordinator.',
          //deleteConfirm: 'Druk op OK om door te gaan.',
          confirms: {
            deleteClientTitle: 'Verwijder client',
            deleteClient: 'Weet u zeker dat u de client wilt verwijderen?',
            deleteReportTitle: 'Verwijder rapport',
            deleteReport: 'Weet u zeker dat u het rapport wilt verwijderen?',
            deleteProfileTitle: 'Verwijder profile',
            deleteProfile: 'Weet u zeker dat u het profiel wilt verwijderen?',
            deleteMemberFromTeamTitle: 'Verwijder het lid uit alle teams',
            deleteMemberFromTeam: 'Weet u zeker dat u het lid uit alle teams wilt verwijderen? Let op: iemand die niet in een team zit, kan TeamUp niet gebruiken. ',
            deleteMemberTitle: 'Verwijderen teamlid',
            deleteMember: 'Weet u zeker dat u het teamlid van het team wil verwijderen?',
            deleteClientGroupTitle: 'Verwijder cliëntengroep',
            deleteClientGroup: 'Weet u zeker dat u deze cliëntengroep wilt verwijderen? Het kan even duren.',
            deleteTeamTitle: 'Verwijderen team',
            deleteTeam: 'Weet u zeker dat u dit team wilt verwijderen? Het kan even duren.',
            deleteTaskTitle: 'Verwijderen taak',
            deleteTask: 'Weet u zeker dat u de taak wilt verwijderen?',
            deleteContactTitle: 'Verwijder contact',
            deleteContact: 'Weet u zeker dat u het contact wilt verwijderen?',
            remove: 'Verwijderen',
            addTeamMemberCodeAsPhoneTitle: 'Teamlidcode wijzigen',
            addTeamMemberCodeAsPhone: 'Er is een eigen teamlidcode ingevoerd, die niet overeen komt met de laatste vier cijfers van uw standaard telefoonnummer?',
            photoRemoveTitle: 'Profielfoto verwijderen',
            photoRemoveBody: 'Weet u zeker dat u de profielfoto wilt verwijderen?',
            yes: 'Ja, dat wil ik',
            no: 'Nee, annuleren',
            cancel: 'Annuleren',
            day: {
              sunday: 'zondag',
              monday: 'maandag',
              tuesday: 'donderdag',
              wednesday: 'woensdag',
              thursday: 'donderdag',
              friday: 'vrijdag',
              saturday: 'zaterdag'
            },
            shortDay: {
             su: "zo",
              mo: "ma",
              tu: "di",
              we: "wo",
              th: "do",
              fr: "vr",
              su: "za"
            }
          },
          deletingTeam: 'Team verwijderen...',
          deletingMember: 'Lid verwijderen ...',
          deletingClient: 'Cliënt verwijderen ...',
          noMessages: 'Er zijn geen berichten.',
          newReport: 'Nieuw rapport',
          editReport: 'Wijzig rapport',
          selectClient: 'Selecteer een cliënt',
          selectMember: 'Selecteer een lid',
          selectMonth: 'Selecteer een maand',
          saveReport: 'Rapport opslaan',
          reportTitle: 'Titel',
          selectSlot: 'Selecteer een periode',
          editClientImg: 'Wijzig foto van de cliënt',
          newTask: 'Nieuwe taak',
          updateTask: 'Wijzig taak',
          managePanelchangePrompt: 'Data is gewijzigd. Klik op \'Ok\' om door te gaan, \'Annuleren\' om te blijven.',
          pagePrevious: 'Vorige',
          pageNext: 'Volgende',
          pageFirst: 'Eerste',
          pageLast: 'Laatste',
          refresh: 'Verversen',
          stateValue: {
            'reachable': 'Bereikbaar',
            'available': 'Beschikbaar',
            'working': 'Aan het werk',
            'offline': 'Offline',
            'not_reachable': 'Niet bereikbaar',
            'on_the_phone': 'Aan de telefoon',
            'unknown': 'Onbekend',
            'reachable': 'Bereikbaar',
            'possibly_reachable': 'Mogelijk bereikbaar',
            'unreachable': 'Niet bereikbaar',
            'unavailable': 'Niet bereikbaar',
            'unknown': 'Offline'
          },
          reportNotExists: 'Rapport bestaat niet.',
          sessionTimeout: 'Uw sessie is verlopen. Graag nogmaals inloggen.'
        },
        task: {
          information: 'Informatie',
          noTasks: 'Geen taken',
          clientName: 'Cliënt',
          memberName: 'Lid',
          orderType1: 'Standaard volgorde',
          orderType2: 'Tijd',
          tasks: 'Taken',
          myTask: 'Mijn taken',
          newTask: 'Nieuwe Taak',
          orderby: 'Sorteer op',
          allTasks: 'Alle taken',
          description: 'Opmerkingen',
          filltheTime: 'Vul de start- en eindtijd in voor de taak.',
          startTimeEmpty: 'Vul de startdatum en -tijd in.',
          endTimeEmpty: 'Vul de einddatum en -tijd in.',
          planTaskInFuture: 'U kunt geen taak in het verleden aanmaken. Selecteer een start- en eindtijd in de toekomst.',
          startLaterThanEnd: 'Beginttijd moet eerder zijn dan de eindtijd.',
          specifyClient: 'Selecteer een cliënt voor deze taak.',
          creatingTask: 'Taak wordt aangemaakt',
          editingTask: 'Taak wordt gewijzigd',
          taskSaved: 'Taak is opgeslagen.',
          deleteTaskConfirm: 'Weet u zeker dat u deze taak permanent wilt verwijderen?',
          taskDeleted: 'Taak verwijderd.',
          planningTime: 'Tijdsbestek',
          refreshTask: 'Het herladen van de taken',
          upload: 'Upload taken',
          deleteTasksConfirm: 'Weet u zeker dat u deze taken permanent wilt verwijderen?',
          taskDescriptionMinChars: 'Opmerkingen moeten uit minimaal 8 karakters bestaan.',
          taskDescriptionMaxChars: 'Het maximaal aantal karakters voor opmerkingen is 500.',
          taskFormValide: 'De nieuwe taak is niet valide, ga eisen onder elk veld na.'
        },
        order: {
          randomOrder: 'Willekeurige',
          fixedOrder: 'Eigen volgorde',
          confirmation: 'Bevestig Keuze',
          randomFeedback: 'Een willekeurige volgorde wordt bepaald.',
          loadTeam: 'Team laden...',
          orderSaved: 'Volgorde opgeslagen'
        },
        logs: {
          loadLogs: 'Logs laden...',
          status: {
            sent: 'Uitgaand',
            received: 'Inkomend',
            finished: 'Afgerond',
            missed: 'Gemist',
            delivered: 'Ontvangen'
          }
        },
        validation: {
          phone: {
            notValid: 'Voer een valide telefoonnummer in!',
            invalidCountry: 'Landcode incorrect! Alleen Nederlandse (+31) nummers toegestaan.',
            tooShort: ' (Telefoonnummer niet correct: te weining nummers.)',
            tooLong: ' (Telefoonnummer niet correct: teveel cijfers.)',
            notValidOnSubmit: 'Vul alstublieft minimaal een geldig telefoonnummer in om op te slaan.',
            message: 'Ingevoerd telefoonnummer is correct. Nummer is geregistreerd in ',
            as: ' als ',
            multipleNotvalid: 'Een of meerdere telefoonnummers zijn niet valide!',
            fixedLine: 'een vast nummer',
            mobile: 'een mobiel nummer',
            mobileOrFixedLine: 'een vast of mobielnummer'
          },
          pincode: {
            exists: 'Kiest u a.u.b. een andere teamlidcode. Deze is in gebruik!'
          },
          password: {
            amountMinChars: function(chars)
            {
              return ' en dient uit minimaal ' + chars + ' teken(s) te bestaan'
            },
            amountMaxChars: function(chars)
            {
              return ' en mag uit maximaal ' + chars + ' tekens(s) te bestaan'
            },
            required: 'Een wachtwoord is verplicht'
          },
          email: {
            notValid: 'Voer een valide e-mailadres in!',
            required: 'Een e-mail is verplicht'
          },
          birthDate: {
            notValid: 'Voer een valide geboortedatum in!'
          },
          userName: {
            regex: 'De gebruikersnaam mag alleen uit alphanummerieke tekens bestaan, inclusief streepjes en onderstreepjes',
            valid: 'Een gebruikersnaam is vereist'
          }
        }
      }
    }
  }
);
