define(
  {
    ui: {
      de: {
        meta: {
          name: 'de',
          label: 'Deutch'
        },
        login: {
          header: 'Anmelden',
          placeholder_username: 'Anwendernamen eingeben',
          placeholder_password: 'Passwort eingeben',
          label_rememberMe: 'Passwort speichern',
          button_login: 'Anmelden',
          button_loggingIn: 'Anmelden...',
          forgot_password: 'Wachtwoord vergeten?',
          forgetPassword: 'Wachtwoord vergeten',
          emailAddress: 'Emailadres',
          resetPassword: 'Wachtwoord opnieuw instellen',
          returnLogin: 'Terugkeren om in te loggen',
          changePassword: 'Passwort ändern',
          downloadApp: 'Download mobiele app',
          ph_username: 'Anwendername',
          ph_password: 'Passwort',
          ph_newPass: 'Passwort ändern',
          ph_retypePass: 'Passwort wiederholen',
          alert_fillfiled: 'Nicht alle Felder sind ausgefüllt',
          alert_wrongUserPass: 'Anwendername oder Passwort nicht korrekt!',
          loading_User: 'Anwenderinformationen laden...',
          loading_Message: 'Nachrichten laden...',
          loading_Group: 'Gruppen laden...',
          loading_Members: 'Team-Mitglieder laden...',
          loading_everything: 'Alles geladen!',
          logout: 'Abmelden',
          loading: 'Laden..',
          loading_clientGroups: 'Patientengruppen laden...',
          loading_clients: 'Patienten laden',
          loading_teams: 'Teams laden...',
          loading_tasks: 'Aufgaben laden...'
        },
        video: {
          stop: 'Het videogesprek is gestopt.'
        },
        dashboard: {
          thisWeek: 'Deze week',
          welcome: 'Welkom',
          everyone: 'Iedereen',
          newMessage: 'Nieuwe berichten',
          goToInbox: 'Ga naar inbox',
          loadingPie: 'Cirkeldiagrammen laden...',
          possiblyReachable: 'Niet gepland',
          noPlanning: 'Geen Planning',
          load: 'laden...',
          time: {
            days: 'd',
            hours: 'u',
            minutes: 'm',
            seconds: 's'
          },
          announcements: 'Alarmberichten',
          loadingP2000: 'Alarmberichten laden...',
          noP2000: 'Er zijn geen alarmberichten.',
          accessibilityStatement: 'Overzichte bereichbarheid',
          loading: 'aan het laden...',
          accessible: 'bereikbaar'
        },
        agenda: {
          planboard: 'Agenda',
          currentAmountReachable: 'Huidig aantal bereikbar',
          amountOfPeopleWished: 'Aantal mensen gewunstnst',
          requiredPeople: 'Benodigd',
          newAvail: 'Neue verfügbarkeit',
          day: 'Tag',
          week: 'Woche',
          month: 'Monat',
          updateAvail: 'Verfügbarkeit aktualisieren',
          from: 'Ab',
          till: 'Bis',
          state: 'Status',
          selectAState: 'Status wählen',
          reoccuring: 'Jede woche',
          lessPeople: 'Es fehlen $v Personen.',
          samePeople: 'Es sind ausreichend Personen vorhanden.',
          morePeople: 'E sind $v Personen zu viel.',
          wished: 'Bedarf',
          combine_reoccuring: 'Es betrifft eine kombinierte planung mit mehreren reihen ?????? ',
          sendMsgToMember: 'Nachricht an Gruppe senden',
          add: 'hinzufügen',
          del: 'löschen',
          change: 'ändern',
          setWish: 'Bedarf speichern',
          timeline: 'Zeitachse',
          statistics: 'Statistiken',
          barCharts: 'Stabdiagramm',
          wishes: 'Bedarf',
          legenda: 'Legende',
          group: 'Team',
          groups: 'Team',
          members: 'Mitglieder',
          teamMembers: 'Team-Mitglieder',
          bothAvailable: 'Both available',
          northAavailable: 'available North',
          southAvailable: 'available South',
          skipperOutService: 'Skipper Of Service',
          notAvailable: 'nicht verfügbar', // nicht verfügbar
          notachieve: 'nicht gespeichert',
          legendaLabels: {
            morePeople: 'Mehr als notwendig',
            enoughPeople: 'Exakt',
            lessPeople: 'Zu wenig'
          },
          lastSyncTime: 'Letzte Synchronisierung:',
          dataRangeStart: 'Anfang Daten-Skala: ',
          DataRangeEnd: 'Ende Daten-Skala: ',
          daterangerToday: 'Heute',
          daterangerTomorrow: 'Morgen',
          daterangerLast7Days: 'Letzte 7 Tage',
          daterangerYesterday: 'Gestern',
          daterangerNext3Days: 'Nächste 3 Tage',
          daterangerNext7Days: 'Nächste 7 Tage',
          loadingTimeline: 'Zeitspanne laden...',
          rangeInfoTotalSelectedDays: 'Zeitraum (Tage): ',
          rangeInfoTime: 'Zeit: ',
          rangeInfoWeekNumber: 'Woche: ',
          rangeInfoMonth: 'Monat: ',
          rangeInfoTotalDays: ', Anzahl Tage: ',
          addTimeSlot: 'Planung hinzufügen...',
          slotAdded: 'Planung erfolgreich hinzugefügt.',
          changingSlot: 'Planung ändern...',
          slotChanged: 'Planung erfolgreich geändert.',
          changingWish: 'Bedarf ändern...',
          wishChanged: 'Bedarf erfolgreich geändert.',
          deletingTimeslot: 'Planung löschen...',
          timeslotDeleted: 'Planung erfolgreich gelöscht.',
          refreshTimeline: 'Zeitachse aktualisieren...',
          preCompilingStortageMessage: 'Bedarfsbericht erstellen',
          weeklyPlanning: 'Meine wöchentliche planung',
          weeklyPlanningOf: 'Wöchentliche planung von ',
          planning: 'Meine planung',
          planningOf: 'Planung von ',
          minNumber: 'Minimum Anzahl benötigt ',
          time: 'Zeit: ',
          weekNumber: 'Woche: ',
          monthNumber: 'Monat: ',
          totalDays: 'Anzahl Tage: ',
          removeTasksRange: function (options)
          {
            if (!_.isUndefined(options))
            {
              var html = 'Sind Sie sicher, dass Sie die Aufgaben von ' + options.range.start + ' bis' + options.range.end;
              html += ' von  ' + options.group + ' ' + options.name;
              html += ' löschen möchten?';
            }

            return html;
          },
          tasksDeleted: function (options)
          {
            if (!_.isUndefined(options))
            {
              var html = 'Die Aufgaben von ' + options.range.start + ' bis' + options.range.end;
              html += ' bis ' + options.group + ' ' + options.name;
              html += ' wurden gelöscht.';
            }

            return html;
          },
          noTasksFounded: 'in diesem Zeitraum gibt es keine Aufgaben ',
          removeTasksTitle: 'Aufgaben löschen'
        },
        planboard: {
          planboard: 'Agenda',
          requiredPeople: 'Benodigd',
          newAvail: 'Neue verfügbarkeit',
          day: 'Tag',
          week: 'Woche',
          month: 'Monat',
          updateAvail: 'Verfügbarkeit aktualisieren',
          from: 'Ab',
          till: 'Bis',
          state: 'Status',
          selectAState: 'Status wählen',
          reoccuring: 'Jede woche',
          lessPeople: 'Es fehlen $v Personen.',
          samePeople: 'Es sind ausreichend Personen vorhanden.',
          morePeople: 'E sind $v Personen zu viel.',
          wished: 'Bedarf',
          combine_reoccuring: 'Es betrifft eine kombinierte Planung mit mehreren Reihen ?????? ',
          sendMsgToMember: 'Nachricht an Gruppe senden',
          add: 'hinzufügen',
          del: 'löschen',
          change: 'ändern',
          setWish: 'Bedarf speichern',
          timeline: 'Zeitachse',
          statistics: 'Statistiken',
          barCharts: 'Stabdiagramm',
          wishes: 'Bedarf',
          legenda: 'Legende',
          group: 'Team',
          groups: 'Team',
          members: 'Mitglieder',
          teamMembers: 'Team-Mitglieder',
          bothAvailable: 'Both available',
          northAavailable: 'available North',
          southAvailable: 'available South',
          skipperOutService: 'Skipper Of Service',
          notAvailable: 'nicht verfügbar', // nicht verfügbar
          notachieve: 'nicht gespeichert',
          legendaLabels: {
            morePeople: 'mehr als notwendig',
            enoughPeople: 'exakt',
            lessPeople: 'zu wenig'
          },
          lastSyncTime: 'Letzte Synchronisierung:',
          dataRangeStart: 'Anfang Daten-Skala: ',
          DataRangeEnd: 'Ende Daten-Skala: ',
          daterangerToday: 'Heute',
          daterangerTomorrow: 'Morgen',
          daterangerLast7Days: 'Letzte 7 Tage',
          daterangerYesterday: 'Gestern',
          daterangerNext3Days: 'Nächste 3 Tage',
          daterangerNext7Days: 'Nächste 7 Tage',
          loadingTimeline: 'Zeitspanne laden...',
          rangeInfoTotalSelectedDays: 'Zeitraum (Tage): ',
          rangeInfoTime: 'Zeit: ',
          rangeInfoWeekNumber: 'Woche: ',
          rangeInfoMonth: 'Monat: ',
          rangeInfoTotalDays: ', Anzahl Tage: ',
          customDates: 'custom Dates',
          addTimeSlot: 'Planung hinzufügen...',
          slotAdded: 'Planung erfolgreich hinzugefügt.',
          changingSlot: 'Planung ändern...',
          slotChanged: 'Planung erfolgreich geändert.',
          changingWish: 'Bedarf ändern...',
          wishChanged: 'Bedarf erfolgreich geändert.',
          deletingTimeslot: 'Planung löschen...',
          timeslotDeleted: 'Planung erfolgreich gelöscht.',
          refreshTimeline: 'Zeitachse aktualisieren...',
          preCompilingStortageMessage: 'Bedarfsbericht erstellen',
          weeklyPlanning: 'Neine wöchentliche planung',
          weeklyPlanningOf: 'Wöchentliche planung von ',
          planning: 'Meine planung',
          planningOf: 'Planung von ',
          minNumber: 'Minimum anzahl benötigt ',
          time: 'Zeit: ',
          weekNumber: 'Woche: ',
          monthNumber: 'Monat: ',
          totalDays: 'Anzahl Tage: ',
          removeTasksRange: function (options)
          {
            if (!_.isUndefined(options))
            {
              var html = 'Sind Sie sicher, dass Sie die Aufgaben von ' + options.range.start + ' bis' + options.range.end;
              html += ' von  ' + options.group + ' ' + options.name;
              html += ' löschen möchten?';
            }

            return html;
          },
          tasksDeleted: function (options)
          {
            if (!_.isUndefined(options))
            {
              var html = 'Die Aufgaben von ' + options.range.start + ' bis' + options.range.end;
              html += ' bis ' + options.group + ' ' + options.name;
              html += ' wurden gelöscht.';
            }

            return html;
          },
          noTasksFounded: 'in diesem Zeitraum gibt es keine Aufgaben ',
          removeTasksTitle: 'Aufgaben löschen'
        },
        options: {
          title: 'Instellingen',
          smsMissedCall: 'SMS bij een gemist gesprek of nieuwe voicemail',
          receiveReachableMembers: 'Bereikbare teamleden ontvangen',
          missedOrVoicemail: 'SMS als het team een gesprek heeft gemist of als er een voicemail is ingesproken',
          hasSms: function (sms)
          {
            return (sms)
              ? 'een'
              : 'geen';
          },
          on: 'Aan',
          off: 'Uit',
          ringingTimeOut: {
            title: 'Rinkeltijd',
            short: 'Bij een langere rinkeltijd hebben teamleden meer tijd om op te nemen, maar de totale wachttijd voor cliënten kan langer zijn als er veel teamleden zijn aangemeld.',
            long: 'Bij een rinkeltijd van meer dan 15 seconden is het aanbevolen dat alle teamleden hun persoonlijke voicemail uitschakelen.',
          },
          personalVoicemailPrevention: 'Persoonlijke voicemailpreventie',
          personalVoicemailPreventionInfo: 'Als deze optie is ingeschakeld, krijgen teamleden eerst de vraag of ze het gesprek willen aannemen van een cli&euml;nt. Door deze optie aan te zetten, kan worden voorkomen dat een cli&euml;nt wordt doorverbonden met de persoonlijke voicemail van een teamlid.',
          voicemailDetectionInfo: 'Bij een rinkeltijd van meer dan 15 seconden is het aanbevolen dat alle teamleden hun persoonlijke voicemail uitschakelen of om gebruik te maken van de persoonlijke voicemailpreventie. Het uitzetten van de persoonlijke voicemail (van de werktelefoon) kunt u regelen bij de telefoonprovider.'
        },
        message: {
          messages: 'Berichten',
          composeAMessage: 'Bericht opstellen',
          compose: 'Opstellen',
          inbox: 'Inbox',
          outbox: 'Outbox',
          trash: 'Prullenbak',
          composeMessage: 'Bericht opstellen',
          close: 'Sluiten',
          broadcast: 'Extra medium',
          sms: 'SMS',
          email: 'Email',
          receviers: 'Ontvanger(s)',
          webTRCWebLink: 'Eine Video-Konferenz wurde gestartet ',
          // troubled
          // chooseRecept: 'Teilnehmer auswählen',
          subject: 'Onderwerp',
          message: 'Bericht',
          sendMessage: 'Bericht versturen',
          sender: 'Zender',
          date: 'Datum',
          questionText: 'Bericht',
          reply: 'Antwoorden',
          del: 'Verwijderen',
          noMessage: 'Er zijn geen berichten.',
          from: 'Van',
          newMsg: 'Nieuw',
          deleteSelected: 'Verwijder geselecteerde berichten',
          someMessage: 'Er zijn $v berichten',
          emptyTrash: 'Prullenbak legen',
          noMsgInTrash: 'Er zijn geen berichten.',
          box: 'Box',
          persons: 'Personen',
          restoreSelected: 'Geselecteerde berichten terugplaatsen',
          loadingMessage: 'Bericht laden...',
          escalation: 'Escalatiebericht',
          reportMessage: 'Nieuw rapport van',
          escalationBody: function (diff, startDate, startTime, endDate, endTime)
          {
            return 'Er is een tekort van ' +
              diff +
              ' mensen tussen ' +
              startDate + ' ' +
              startTime + ' en ' +
              endDate + ' ' +
              endTime + '. ' +
              'Zet uzelf a.u.b. op bereikbaar indien u bereikbaar bent voor die periode';
          },
          removed: 'Bericht succesvol verwijderd.',
          removing: 'Bericht verwijderen...',
          refreshing: 'Bericht vernieuwen...',
          removingSelected: 'Geselecteerde berichten verwijderen...',
          restoring: 'Bericht terugplaatsen...',
          restored: 'Bericht succesvol teruggeplaatst.',
          restoringSelected: 'Geselecteerde berichten terugplaatsen...',
          emptying: 'Prullenbak leegmaken...',
          emptied: 'Prullenbak succesvol geleegd.',
          sending: 'Bericht versturen...',
          sent: 'Bericht verstuurd.',
          typeSubject: 'Vul een onderwerp in.',
          // messages: 'Berichten',
          ph_filterMessage: 'Berichten filteren...',
          noReceivers: 'Selecteer een ontvanger',
          emptyMessageBody: 'Het bericht is leeg, typ a.u.b. een bericht.',
          send: 'Versturen'
        },
        groups: {
          groups: 'Gruppen',
          newGroup: 'neue Gruppe',
          newMember: 'neues Team-Mitglied',
          search: 'Zoeken',
          addNewGroup: 'neue Gruppe hinzufügen',
          editGroup: 'Gruppe ändern',
          searchResults: 'Zoekresultaten',
          group: 'Gruppe',
          close: 'beenden',
          name: 'Name',
          saveGroup: 'Gruppe speichern',
          registerMember: 'Mitglied hinzufügen',
          role: 'Funktion',
          selectRole: 'Funktion hinzufügen',
          // troubled
          // selectGroup: 'Gruppe auswählen',
          //
          email: 'Email',
          phone: 'Telefon',
          address: 'Adresse',
          postCode: 'Postleitzahl',
          tel: 'Telefonnummer',
          city: 'Wohnort',
          userName: 'Anwendername',
          password: 'Passwort',
          saveMember: 'Mitglied speichern',
          serachFor: 'Zoekresultaten voor ',
          sorryCanNotFind: 'Sorry, geen resultaten.',
          addToGroup: 'der Gruppe hinzufügen',
          addMemberToGroup: 'ausgewählte(n) Teilnehmer der Gruppe hinzufügen',
          resultCount: 'Er zijn $v resultaten.',
          deleteGroup: 'Gruppe löschen',
          noMembers: 'keine Mitglieder in dieser Gruppe.',
          removeSelectedMembers: 'ausgewählte Mitglieder löschen',
          memberCount: 'Es gibt $v Mitglieder.',
          searchingMembers: 'Mitglieder suchen...',
          addingNewMember: 'neues Mitglied hinzufügen...',
          memberAdded: 'Mitglied erfolgreich dieser Gruppe hinzugefügt.',
          refreshingGroupMember: 'Gruppen- und Mitgliederliste aktualisieren...',
          removingMember: 'Mitglied aus dieser Gruppe löschen...',
          memberRemoved: 'Mitglied erfolgreich aus dieser Gruppe gelöscht.',
          removingSelected: 'ausgewählte Mitglieder löschen...',
          saving: 'Gruppe speichern...',
          groupSaved: 'Gruppe erfolgreich gespeichert.',
          registerNew: 'neues Mitglied hinzufügen...',
          memberRegstered: 'Mitglied erfolgreich hinzugefügt.',
          deleting: 'Gruppe löschen...',
          deleted: 'Gruppe erfolgreich gelöscht.',
          filterMembers: 'Teamleden filteren...',
          searchfor: 'voornaam, achternaam..'
        },
        profile: {
          profile: 'Profil',
          edit: 'ändern',
          password: 'Wachtwoord',
          timeline: 'Tijdlijn',
          profileView: 'Profilwiedergabe',
          userGroups: 'Anwendergruppen',
          role: 'Funktion',
          email: 'Email',
          phone: 'Telefon',
          address: 'Adresse',
          postcode: 'Postleitzahl',
          city: 'Wohnort',
          editProfile: 'Profil ändern',
          name: 'Name',
          saveProfile: 'Profil speichern',
          passChange: 'Passwort ändern',
          currentPass: 'aktuelles Passwort',
          newPass: 'neues Passwort',
          newPassRepeat: 'neues Passwort wiederholen',
          changePass: 'Passwort ändern',
          newAvail: 'Nieuwe bereikbaarheid',
          userName: 'Anwendername',
          pincode: 'teamlidcode',
          // saveProfile: 'Profilinformationen speichern...',
          refreshing: 'Profielinformatie vernieuwen...',
          dataChanged: 'Profildaten erfolgreich geändert.',
          savingPassword: 'neues Passwort speichern...',
          passwordChanged: 'Passwort erfolgreich aktualisiert.',
          passwordSavedFailed: 'Passwort aktualisieren fehlgeschlagen.',
          pleaseFill: 'Nicht alle Felder sind ausgefüllt!',
          passNotMatch: 'Passwort-Einträge stimmen nicht überein.',
          changingPass: 'Passwort ändern...',
          passChanged: 'Passwort erfolgreich geändert.',
          passwrong: 'Passwort ist inkorrekt. Eingabe wiederholen.',
          currentPassWrong: 'Das aktuelle Passwort ist inkorrekt. Eingabe wiederholen.',
          newTimeslotAdded: 'Nieuw tijdslot succesvol toegevoegd.',
          changingTimeslot: 'Tijdslot wijzigen...',
          timeslotChanged: 'Tijdslot succesvol gewijzigd.',
          exampleBirthDate: 'Beispiel: 31-12-2001 ',
          firstName: 'Vorname',
          lastName: 'Nachname',
          editProfileImg: 'Profilbild ändern',
          profileImgSuccessfullyUploaded: 'Profilbild erfolgreich hochgeladen.',
          loadUploadURL: 'Bild hochladen, URL laden',
          click2upload: 'Klicken Sie hier, um hochzuladen',
          birthday: 'Geburtsdatum',
          username: 'Anwendername',
          retypePassword: 'Passwort wiederholen',
          roleChangePrompt: 'Ihre Rolle ändert sich hiermit. Sie werden automatisch abgemeldet. Klicken Sie "Ok", um die Änderung durchzuführen.',//'You changed your own role, system will automatically logout, press "Yes" to continue.',
          specifyTeam: 'Wählen Sie eine Gruppe für diese Anwender.',//'You need to sepcify a team to this user'
          authorInfo: 'Erfasser-Info laden...',
          changePassWord: 'Passwort ändern',
          safePassword: 'Passwort speichern',
          oldPassword: 'altes Passwort',
          pincode: 'Teamlidcode',
          pincodeInUse: 'Deze teamlidcode is in gebruik. Kies een andere.',
          pincodeNotValid: 'Vul a.u.b. een geldige teamlidcode van maximaal 8 cijfers in!',
          pincodeCorrect: 'Deze teamlidcode is in gebruik of niet geldig! Vul a.u.b. een geldige teamlidcode.',
          pincodeInfo: 'Bovenstaande code kunt u telefonisch gebruiken om u aan te melden als TeamTelefoon uw nummer niet herkent.',
          duplicateNumber: 'Nummer bestaat al. Andere nummer invoeren aub.',
          pincodeInfoPhone: 'De laatste vier cijfers van dit telefoonnummer worden gebruikt voor de teamlidcode, tenzij deze zelf wordt opgegeven.'
        },
        settings: {
          settings: 'Einstellungen',
          user: 'Anwender',
          application: 'Applicatie',
          userSettings: 'Gebruikersinstellingen',
          appSettings: 'Applicatie-instellingen',
          saveSettings: 'Instellingen opslaan',
          langSetting: 'Taal',
          saving: 'Einstellungen speichern...',
          refreshing: 'Einstellungen aktualisieren...',
          saved: 'Einstellungen erfolgreich gespeichert.',
          selectTeam: 'Gruppe wählen',
          teamSettings: 'Einstellungen, Gruppen-Name',
          ringtime: 'Rufdauer',
          ButtonSaveChoice: 'Auswahl bestätigen'
        },
        help: {
          header: 'Hilfe & Support',
          support: 'Support',
          teamTelephone: {
            setReachabilityPhone: 'Hoe geef ik telefonisch mijn bereikbaarheid door?',
            setReachabilityWeb: 'Hoe wijzig ik mijn bereikbaarheid in de web applicatie?',
            changeReachabilityTeamMember: 'Hoe wijzig ik de bereikbaarheid van een teamlid?',
            changeCallOrderTeam: 'Hoe wijzig ik de belvolgorde van mijn team?',
            changeCallOptions: 'Hoe wijzig ik de belinstellingen van mijn team?'
          },
          teams: {
            addNewMember: 'Hoe voeg ik een nieuw lid toe aan mijn team?',
            addExistingMember: 'Hoe voeg ik een nieuw lid toe aan mijn team?',
            removeMember: 'Hoe verwijder ik een lid uit mijn team?'
          },
          web: {
            title: 'Web Anwendung',
            newMember: 'Wie kann ich einen neuen Patienten anlegen?'
          },
          manuelTeamTelephone: {
            title: 'Handbuch TeamTelefon',
            download: 'Handbuch herunterladen',
          },
          android: {
            title: 'Android',
            addClientReport: 'Wie kann ich einem Patienten einen Bericht hinzufügen?',
            callClient: 'Wie kann ich einen Kunden anrufen?',
          }
        },
        downloads: {
          app: 'Binnenkort te downloaden.',
          manual: 'Handbuch herunterladen'
        },
        loading: {
          general: 'laden',
          manage: 'verwalten',
          dashboard: 'Dashboard',
          planboard: 'Agenda',
          messages: 'Berichte',
          teams: 'Gruppen',
          profile: 'Profil',
          settings: 'Einstellungen'
        },
        teamup: {
          apply: 'Anwenden',
          hour: 'stunde',
          teams: 'Gruppen',
          selectTeam: 'Gruppe auswählen',
          clients: 'Patienten',
          logs: 'Logs',
          order: 'Auftrag',
          options: 'Instellungen',
          selectClientGroup: 'Patientengruppe wählen',
          loadMembersByName: 'Mitglieder laden...',
          loadingMembers: 'Mitglieder suchen...',
          howToSearchMembers: 'Mitglieder suchen per Anfangsbuchstaben des Vor- und/oder Nachnamens.',
          selectClientGroup: 'Patientengruppe wählen',
          manage: 'verwalten',
          teamTelephone: 'Team-telefon',
          chooseTeam: 'Gruppe wählen',
          undefinedTeamMember: 'unbekanntes Gruppen-Mitglied',
          defaultTeam: 'Standard Gruppe',
          edit: 'bearbeiten',
          editTeam: 'Gruppe bearbeiten',
          team: 'Gruppe',
          del: 'löschen',
          noMembers: 'Keine gruppen-mitglieder',
          newTeam: 'Neue gruppe',
          teamName: 'Gruppen-Name',
          createTeam: 'Speichern',
          newMember: 'Neues gruppen-mitglied',
          noMembersFound: 'kein Ergebnis für diese Suche.',
          name: 'Name',
          role: 'Rolle',
          phone: 'Telefon',
          street: 'Strasse',
          postCode: 'Postleitzahl',
          city: 'Ortsname',
          email: 'E-Mail',
          saveMember: 'speichern',
          state: 'Status',
          states: 'Status',
          saveTeam: 'Gruppe speichern',
          save: 'speichern',
          refreshing: 'Gruppen-Informationen aktualisieren',
          dataChanged: 'Informationen wurden geändert.',
          teamSubmitError: 'Fehler beim Erstellen: ',
          queryTeamError: 'Fehler bei Gruppe-Suche aufgetreten.',
          teamNamePrompt1: 'Gruppen-Namen eintragen.',
          teamNamePrompt2: 'Kontaktdaten hinzufügen',
          cancel: 'Abbrechen',
          chooseRole: 'Rolle wählen',
          func: 'Funktion',
          chooseFunction: 'Funktion wählen',
          newClientGroup: 'neue Gruppe',
          newClient: 'neuer Patient',
          reports: 'Berichte',
          report: 'Bericht',
          noClients: 'keine Patienten in dieser Gruppe',
          noClientGroup: 'keine Patienten-Gruppe',
          TeamClients: 'Gruppe - Patienten',
          createClientGroup: 'speichern',
          contacts: 'Kontakte',
          Number: 'Nummer',
          clientProfileUrl: 'URL Patientenprofil',
          addContact: 'Ansprechpartner hinzufügen',
          editContact: 'Ansprechpartner ändern',
          saveClient: 'speichern',
          group: 'Gruppe',
          errorSaveClientGroup: 'Speichern von Änderungen der Kunden-Gruppe ist fehlgeschlagen.',
          noContacts: 'keine Ansprechpartner vorhanden.',
          noReports: 'keine Berichte für diesen Patienten.',
          contactCount: 'Es gibt $v Ansprechpartner.',
          reportCount: 'Es gibt $v Berichte.',
          accountInfoFill: 'Account-Informationen eintragen',
          passNotSame: 'Passwörter stimmen nicht überein.',
          savingMember: 'Mitglied speichern...',
          selectTeam: 'Gruppe wählen',
          clinetInfoFill: 'Patienteninformationen (Name, Telefonnummer, ...) eintragen',
          savingClient: 'Patienteninformationen speichern...',
          clientSubmitError: 'Fehler beim Anlegen eines neuen Patienten.',
          clientGroups: 'Patienten-Gruppen',
          saveClientGroup: 'Patienten-Gruppe speichern...',
          deleteClientFromClientGroup: 'Patient wurde gelöscht',
          deletingClientFromClientGroup: 'Patient aus Gruppe löschen...',
          teams_Cap: 'Gruppen',
          noTeamNameFound: 'unbekannter Gruppenname',
          noTeam: 'keine Gruppe',
          searchMembers: 'Mitglieder suchen...',
          editClient: 'Patient bearbeiten',
          loadingNumber: 'Telefonnummer der Gruppe wird geladen...',
          loadClients: 'Patienteninformationen werden geladen...',
          birthdayError: 'Geburtsdatum ist ungültig.',
          map: 'Karte',
          saveContacts: 'Ansprechpartner speichern',
          loadingReports: 'Berichte laden',
          reportEmpty: 'Titel und Zusammenfassung eintragen!',
          reportValid: 'Eingabefelder nicht korrekt!',
          reportBody: 'Umschreibung',
          reportBodyRequired: 'Umschreibung eintragen',
          reportTitleRequired: 'Überschrift eintragen',
          reportBodyMinChars: 'Umschreibung sollte mindestens 8 Zeichen enthalten!',
          reportTitleMinChars: 'Überschrift sollte mindestens 4 Zeichen enthalten!',
          reportBodyMaxChars: 'Die Umschreibung darf maximal 150 Zeichen enthalten!',
          reportTitleMaxChars: 'Die Überschrift darf maximal 30 Zeichen enthalten!',
          checkLocalStorage: 'Der von Ihnen eingeschaltete Privat-Modus wird nicht unterstützt. Hier erfahren Sie, wie der Privat-Modus ausgeschaltet wird:',
          readMore: 'mehr erfahren',
          date: 'Datum',
          datetime: 'Datum und Zeit',
          writenBy: 'erfasst von',
          noSharedStates: 'kein geteilter Status',
          savingContacts: 'Ansprechpartner speichern',
          // delClientGroupConfirm: 'Soll diese Patienten-Gruppe tatsächlich gelöscht werden? Dies kann einen Moment dauern.',
          // delTeamConfirm: 'Soll diese Gruppe tatsächlich gelöscht werden? Dies kann einen Moment dauern.',
          deletingClientGroup: 'Gruppe löschen... ',
          from: 'von',
          to: 'Bis',
          time: 'Zeit',
          duration: 'Dauer',
          coordinatorNoTeam: 'Sie sind in keiner Gruppe; Tragen Sie sich in eine Gruppe ein.',
          teamMemberNoTeam: 'Sie sind in keiner Gruppe, bitte nehmen Sie Kontakt mit dem Verwalter auf. ',
          //deleteConfirm: 'OK klicken, um weiter zu machen.',
          confirms: {
            deleteClientTitle: 'Patient löschen',
            deleteClient: 'Soll dieser Patient tatsächlich gelöscht werden?',
            deleteClientFromTeamTitle: 'Patient aus Gruppe löschen',
            deleteClientFromTeam: 'Sind Sie sicher, dass dieser patient aus dieser gruppe gelöscht werden soll?',
            deleteReportTitle: 'Bericht löschen',
            deleteReport: 'Sind Sie sicher, dass dieser bericht gelöscht werden soll?',
            deleteProfileTitle: 'Profil löschen',
            deleteProfile: 'Sind Sie sicher, dass dieses profil gelöscht werden soll?',
            deleteMemberFromTeamTitle: 'Mitglied aus allen gruppen löschen',
            deleteMemberFromTeam: 'Sind Sie sicher, dass dieses Mitglied aus allen gruppen gelöscht werden soll? Achtung, wer nicht in einer Gruppe ist, kann TeamUp nicht anwenden!',
            deleteMemberTitle: 'Mitglied löschen',
            deleteMember: ' Sind Sie sicher, dass dieses Mitglied aus der gruppe gelöscht werden soll?',
            deleteClientGroupTitle: 'Kunden-Gruppe löschen',
            deleteClientGroup: ' Sind Sie sicher, dass diese kunden-gruppe gelöscht werden soll? Dies kann einen moment dauern.',
            deleteTeamTitle: 'Gruppe löschen',
            deleteTeam: ' Sind Sie sicher, dass diese Gruppe gelöscht werden soll? Dies kann einen moment dauern.',
            deleteTaskTitle: 'Aufgabe löschen',
            deleteTask: ' Sind Sie sicher, dass diese Aufgabe gelöscht werden soll? ',
            deleteContactTitle: 'Ansprechpartner löschen',
            deleteContact: ' Sind Sie sicher, dass dieser ansprechpartner gelöscht werden soll?',
            remove: 'löschen',
            addTeamMemberCodeAsPhoneTitle: 'Teamlidcode wijzigen',
            addTeamMemberCodeAsPhone: 'Er is een eigen teamlidcode ingevoerd, die niet overeen komt met de laatste vier cijfers van uw standaard telefoonnummer?',
            photoRemoveTitle: 'Profilbild löschen',
            photoRemoveBody: ' Sind Sie sicher, dass Ihr profilbild gelöscht werden soll?',
            yes: 'Ja, das möchte ich',
            no: 'Nein, abbrechen',
            cancel: 'abbrechen',
            day: {
              sunday: 'Sonntag',
              monday: 'Montag',
              tuesday: 'Dienstag',
              wednesday: 'Mittwoch',
              thursday: 'Donnerstag',
              friday: 'Freitag',
              saturday: 'Samstag'
            },
            shortDay: {
              su: "So",
              mo: "Mo",
              tu: "Di",
              we: "Mi",
              th: "Do",
              fr: "Fr",
              su: "Sa"
            }
          },
          deletingTeam: 'Gruppe löschen...',
          deletingMember: 'Mitglied löschen ...',
          deletingClient: 'Patient löschen ...',
          noMessages: 'Es gibt keine Berichte.',
          newReport: 'neuer Bericht',
          editReport: 'Bericht ändern',
          selectClient: 'Patient wählen',
          selectMember: 'Mitglied wählen',
          selectMonth: 'Monat wählen',
          saveReport: 'Bericht speichern',
          reportTitle: 'Titel',
          selectSlot: 'Zeitraum wählen',
          editClientImg: 'Patientenbild ändern',
          newTask: 'neue Aufgabe',
          updateTask: 'Aufgabe ändern',
          managePanelchangePrompt: 'Daten wurden geändert. Auf \'Ok\' klicken, um fortzufahren, ansonsten \'Abbrechen\' .',
          pagePrevious: 'vorherige',
          pageNext: 'nächste',
          pageFirst: 'erste',
          pageLast: 'letzte',
          refresh: 'aktualisieren',
          stateValue: {
            'reachable': 'Erreichbar',
            'available': 'Erreichbar',
            'working': 'Eeschäftigt',
            'offline': 'Off-line',
            'not_reachable': 'Nicht erreichbar',
            'on_the_phone': 'Am Telefon',
            'unknown': 'Unbekannt',
            'reachable': 'Erreichbar',
            'possibly_reachable': 'Nichts geplant',
            'unreachable': 'Nicht erreichbar',
            'unavailable': 'Nicht verfügbar',
            'unknown': 'Off-line'
          },
          reportNotExists: 'Bericht nicht vorhanden.',
          sessionTimeout: 'Sitzung beendet, Sie müssen sich erneut anmelden.',
          errorCode: {
              '1': 'Onbekende foutmelding',
              '2': 'De Deomeinagent is niet gevonden. Opnieuw inloggen zou dit probleem op kunnen lossen.',
              '3': 'Dit lid moet de rol van coördinator hebben, voordat er een team aangemaakt kan worden',
              '4': 'Eeen agent id mag alleen uit alpha nummerieke karakters, onder- en streepjes bestaan',
              '5': 'Kan de JSON niet parsen of de JSON body',
              '6': 'Een of meerdere paramters zijn er niet',
              '7': 'De group "members" is niet gevonden',
              '8': 'Team met het gegeven teamUuid bestaat niet',
              '9': 'Dit lid maakt geen deel uit van het team',
              '10': 'Team met het gegeven teamUuid bestaat niet',
              '11': 'Dit lid moet de rol van coördinator hebben, voordat er een nieuw team aangemaakt kan worden',
              '12': 'De team agent kon niet aangemaakt worden',
              '13': 'De uuid parameter en het uuid in de payload komen niet overheen',
              '14': 'Een lid met dit uuid bestaat al',
              '15': 'Een van de meegstuurde waardes is onbekend',
              '16': 'Een van de volgende settings heeft als waarde null, Dit is niet mogelijk',
              '17': 'Een van de meegestuurde waardes heeft een onbekend type',
              '18': 'De gebruiker met het opgegeven id bestaat niet',
              '19': 'Het ingevoerde oude wachtwoord komt niet overheen met het huidige',
              '20': 'Dit lid moet de rol van coördinator hebben, voordat er een wachtwoord van een ander lid gewijzigd kan worden',
              '21': 'Een parameter kan niet geparst worden',
              '22': 'Dit lid is in geen enkel team'
          },
        },
        task: {
          information: 'Informatie',
          noTasks: 'Geen taken',
          clientName: 'Cliënt',
          memberName: 'Lid',
          orderType1: 'Standaard volgorde',
          orderType2: 'Tijd',
          tasks: 'Taken',
          myTask: 'Mijn taken',
          newTask: 'Nieuwe Taak',
          orderby: 'Sorteer op',
          allTasks: 'Alle taken',
          description: 'Opmerkingen',
          filltheTime: 'Vul de start- en eindtijd in voor de taak.',
          startTimeEmpty: 'Vul de startdatum en -tijd in.',
          endTimeEmpty: 'Vul de einddatum en -tijd in.',
          planTaskInFuture: 'U kunt geen taak in het verleden aanmaken. Selecteer een start- en eindtijd in de toekomst.',
          startLaterThanEnd: 'Beginttijd moet eerder zijn dan de eindtijd.',
          specifyClient: 'Selecteer een cliënt voor deze taak.',
          creatingTask: 'Taak wordt aangemaakt',
          editingTask: 'Taak wordt gewijzigd',
          taskSaved: 'Taak is opgeslagen.',
          deleteTaskConfirm: 'Weet u zeker dat u deze taak permanent wilt verwijderen?',
          taskDeleted: 'Taak verwijderd.',
          planningTime: 'Tijdsbestek',
          refreshTask: 'Het herladen van de taken',
          upload: 'Upload taken',
          deleteTasksConfirm: 'Weet u zeker dat u deze taken permanent wilt verwijderen?',
          taskDescriptionMinChars: 'Opmerkingen moeten uit minimaal 8 karakters bestaan.',
          taskDescriptionMaxChars: 'Het maximaal aantal karakters voor opmerkingen is 500.',
          taskFormValide: 'De nieuwe taak is niet valide! Ga de eisen onder elk veld na.'
        },
        order: {
          randomOrder: 'Willekeurige',
          fixedOrder: 'Eigen volgorde',
          confirmation: 'Bevestig Keuze',
          randomFeedback: 'Een willekeurige volgorde wordt bepaald.',
          loadTeam: 'Team laden...',
          orderSaved: 'Volgorde opgeslagen',
          noMembers: 'Er zijn geen leden in dit team.'
        },
        logs: {
          loadLogs: 'Logs laden...',
          empty: 'Er zijn Nein logs',
          filter: 'Filterung logs...',
          status: {
            sent: 'Uitgaand',
            received: 'Inkomend',
            finished: 'Afgerond',
            missed: 'Gemist',
            delivered: 'Ontvangen',
            error: 'Fout'
          }
        },
        validation: {
          phone: {
            notValid: 'Voer een valide telefoonnummer in!',
            invalidCountry: 'Landcode incorrect! Alleen Nederlandse (+31) nummers toegestaan.',
            tooShort: ' (Telefoonnummer niet correct: te weining nummers.)',
            tooLong: ' (Telefoonnummer niet correct: teveel cijfers.)',
            notValidOnSubmit: 'Vul alstublieft minimaal een geldig telefoonnummer in om op te slaan.',
            message: 'Ingevoerd telefoonnummer is correct. Nummer is geregistreerd in ',
            as: ' als ',
            multipleNotvalid: 'Een of meerdere telefoonnummers zijn niet valide!',
            fixedLine: 'een vast nummer',
            mobile: 'een mobiel nummer',
            mobileOrFixedLine: 'een vast of mobielnummer'
          },
          pincode: {
            exists: 'Kiest u a.u.b. een andere teamlidcode. Deze is in gebruik!'
          },
          password: {
            amountMinChars: function (chars)
            {
              return ' en dient uit minimaal ' + chars + ' teken(s) te bestaan'
            },
            amountMaxChars: function (chars)
            {
              return ' en mag uit maximaal ' + chars + ' tekens(s) te bestaan'
            },
            oldPassMatch: 'Het ingevulde oude wachtwoord komt niet overheen met het huidige.',
            required: 'Een wachtwoord is verplicht'
          },
          email: {
            notValid: 'Voer een valide e-mailadres in!',
            required: 'Een e-mail is verplicht'
          },
          role: 'Kies een rol!',
          birthDate: {
            notValid: 'Voer een valide geboortedatum in!'
          },
          userName: {
            regex: 'De gebruikersnaam mag alleen uit alphanummerieke tekens bestaan, inclusief streepjes en onderstreepjes',
            valid: 'Een gebruikersnaam is vereist'
          },
          search: {
            notValid: 'Voer een voor en/of achternaam in!'
          }
        }
      },
      nl: {
        meta: {
          name: 'nl',
          label: 'Nederlands'
        },
        login: {
          header: 'Inloggen',
          placeholder_username: 'Vul uw gebruikersnaam in',
          placeholder_password: 'Vul uw wachtwoord in',
          label_rememberMe: 'Onthoud mij',
          button_login: 'Inloggen',
          button_loggingIn: 'Inloggen...',
          forgot_password: 'Wachtwoord vergeten?',
          forgetPassword: 'Wachtwoord vergeten',
          emailAddress: 'Emailadres',
          resetPassword: 'Wachtwoord opnieuw instellen',
          returnLogin: 'Terugkeren om in te loggen',
          changePassword: 'Wachtwoord wijzigen',
          downloadApp: 'Download mobiele app',
          ph_username: 'Gebruikersnaam',
          ph_password: 'Wachtwoord',
          ph_newPass: 'nieuw wachtwoord',
          ph_retypePass: 'Herhaal wachtwoord',
          alert_fillfiled: 'Vul alle velden in!',
          alert_wrongUserPass: 'Onjuiste gebruikersnaam of wachtwoord!',
          loading_User: 'Gebruikersinformatie laden...',
          loading_Message: 'Berichten laden...',
          loading_Group: 'Groepen laden...',
          loading_Members: 'Teamleden laden...',
          loading_everything: 'Alles is geladen!',
          logout: 'Uitloggen',
          loading: 'Laden..',
          loading_clientGroups: 'Cliëntengroepen laden...',
          loading_clients: 'Clienten laden',
          loading_teams: 'Teams laden...',
          loading_tasks: 'Taken laden...'
        },
        video: {
          stop: 'Het videogesprek is gestopt.'
        },
        dashboard: {
          thisWeek: 'Deze week',
          welcome: 'Welkom',
          everyone: 'Iedereen',
          newMessage: 'Nieuwe berichten',
          goToInbox: 'Ga naar inbox',
          loadingPie: 'Cirkeldiagrammen laden...',
          possiblyReachable: 'Niet gepland',
          noPlanning: 'Geen Planning',
          load: 'laden...',
          time: {
            days: 'd',
            hours: 'u',
            minutes: 'm',
            seconds: 's'
          },
          announcements: 'Alarmberichten',
          loadingP2000: 'Alarmberichten laden...',
          noP2000: 'Er zijn geen alarmberichten.',
          accessibilityStatement: 'Overzicht bereikbaarheid',
          loading: 'aan het laden...',
          accessible: 'bereikbaar'
        },
        agenda: {
          requiredPeople: 'Benodigd',
          newAvail: 'Nieuwe bereikbaarheid',
          day: 'Dag',
          week: 'Week',
          month: 'Maand',
          updateAvail: 'Update bereikbaarheid',
          from: 'Vanaf',
          till: 'Tot',
          state: 'Status',
          selectAState: 'Selecteer een status',
          reoccuring: 'Elke week',
          lessPeople: 'Er zijn $v mensen te weinig als nodig.',
          samePeople: 'Er zijn net zoveel mensen als nodig.',
          morePeople: 'Er zijn $v mensen meer als nodig.',
          noMembers: 'Dit team heeft geen leden',
          wished: 'Behoefte',
          combine_reoccuring: 'Dit is een gecombineerde planning rij met opeenvolgende rijen.',
          sendMsgToMember: 'Send Message To Members',
          add: 'Toevoegen',
          del: 'Verwijderen',
          change: 'Wijzigen',
          setWish: 'Behoefte opslaan',
          timeline: 'Tijdlijn',
          statistics: 'Statistics',
          barCharts: 'Staafdiagrammen',
          wishes: 'Behoefte',
          legenda: 'Legenda',
          group: 'Team',
          groups: 'Team',
          members: 'Leden',
          teamMembers: 'Teamleden',
          bothAvailable: 'Both available',
          northAavailable: 'available North',
          southAvailable: 'available South',
          skipperOutService: 'Skipper Of Service',
          notAvailable: 'Niet bereikbaar', // Niet Beschikbaar
          notachieve: 'Niet gearchieveerd',
          legendaLabels: {
            morePeople: 'Ruim genoeg mensen',
            enoughPeople: 'Precies genoeg mensen',
            lessPeople: 'Te weinig mensen'
          },
          lastSyncTime: 'Laatste synchronisatie tijd:',
          dataRangeStart: 'Datumbereik start: ',
          DataRangeEnd: 'Datumbereik eind: ',
          loadingTimeline: 'Tijdlijn laden...',
          addTimeSlot: 'Tijdslot toevoegen...',
          slotAdded: 'Nieuw tijdslot is succesvol toegevoegd',
          changingSlot: 'Tijdslot wijzigen...',
          slotChanged: 'Tijdslot succesvol gewijzigd.',
          changingWish: 'Behofte wordt veranderd...',
          wishChanged: 'De behoefte is succesvol gewijzigd.',
          deletingTimeslot: 'Tijdslot verwijderen...',
          timeslotDeleted: 'Tijdslot is succesvol verwijderd.',
          refreshTimeline: 'Tijdlijn refreshen...',
          preCompilingStortageMessage: 'Voor gecompileert kort bericht',
          weeklyPlanning: 'Weekelijkse planninng',
          planning: 'Mijn planning',
          planningOf: 'Planning van ',
          minNumber: 'Minimum aantal benodigden',
          statDays: 'dagen',
          statHours: 'uren',
          statMinutes: 'minuten',
          statPeopleLess: 'Less people than expected',
          statPeopleEven: 'Precies genoeg mensen',
          statPeopleMore: 'Meer mensen dan verwacht',
          getWishes: 'Pak de minimale benodigde waarde...',
          daterangerToday: 'Vandaag',
          daterangerTomorrow: 'Morgen',
          daterangerYesterday: 'Gisteren',
          daterangerNext3Days: 'Volgende 3 dagen',
          daterangerNext7Days: 'Volgende 7 dagen',
          rangeInfoTotalSelectedDays: 'Totaal geselecteerde dagen: ',
          rangeInfoTime: 'Tijd: ',
          rangeInfoWeekNumber: 'Weeknummer: ',
          rangeInfoMonth: 'Maand: ',
          rangeInfoTotalDays: ', Totaal aantal dagen: ',
          query: 'Er zijn wat problemen met het synchroniseren van de agenda. Kunt u alstublieft uw browser verversen om de laatste informatie op te halen.',
          pastAdding: 'Het is niet mogelijk in het verleden te plannen!',
          errorAdd: 'Error with adding a new planning!',
          errorChange: 'Error with changing planning!',
          pastChanging: 'Het wijzigen van een planning in het verleden is niet mogelijk!',
          pastDeleting: 'Het verwijderen van een planning in het verleden is niet mogelijk!',
          remove: 'Fout(en) met het verwijderen van de planning!',
          wisher: 'Fout(en) met het wijzigen van de behoefte',
          editTimeline: 'Wijzig de tijdlijn van ',
          notAuth: 'Het is niet mogelijk om iemands anders planning te wijzigen, behalve als de rol van coordinator. Als coordinator kan je de planning van andere wijzigen  door op hun naam te klikken in de lijst. Je wordt naar een andere pagina genavigeerd waar de planning van het betreffende lid is te wijzigen.'
        },
        planboard: {
          planboard: 'Agenda',
          newAvail: 'Nieuwe bereikbaarheid',
          day: 'Dag',
          week: 'Week',
          month: 'Maand',
          updateAvail: 'Update bereikbaarheid',
          from: 'Van',
          till: 'Tot',
          state: 'Status',
          customDates: 'Aangepaste periode',
          selectAState: 'selecteer een status',
          reoccuring: 'Herhaling',
          lessPeople: 'Er is een tekort van $v mens(en)!',
          samePeople: 'Er zijn precies genoeg mensen.',
          morePeople: 'Er is een overschot van $v mens(en)!',
          wished: 'Gewenst',
          combine_reoccuring: 'Dit is een gecombineerde planning.',
          sendMsgToMember: 'Stuur bericht naar leden',
          noMembers: 'Er zijn geen leden in dit team.',
          noClients: 'Er zijn geen clienten in deze clientgroep.',
          add: 'Toevoegen',
          del: 'Verwijderen',
          change: 'Wijzigen',
          setWish: 'Behoefte instellen',
          timeline: 'Tijdlijn',
          statistics: 'Statistieken',
          barCharts: 'Staafdiagrammen',
          wishes: 'Behoefte',
          legenda: 'Legenda',
          group: 'Groep',
          groups: 'Groepen',
          members: 'Leden',
          teamMembers: 'Teamleden',
          bothAvailable: 'Beide bereikbaar',
          northAavailable: 'Beschikbaar Noord',
          southAvailable: 'Beschikbaar Zuid',
          skipperOutService: 'Schipper van dienst',
          notAvailable: 'Niet bereikbaar',
          notachieve: 'Niet behaald',
          legendaLabels: {
            morePeople: 'Meer mensen',
            enoughPeople: 'Precies genoeg mensen',
            lessPeople: 'Te weinig mensen'
          },
          lastSyncTime: 'Laatste synchronisatietijd:',
          dataRangeStart: 'Begin gegevensscala: ',
          DataRangeEnd: 'Eind gegevensscala: ',
          daterangerToday: 'Vandaag',
          daterangerTomorrow: 'Morgen',
          daterangerLast7Days: 'Laatste 7 dagen',
          daterangerYesterday: 'Gisteren',
          daterangerNext3Days: 'Volgende 3 dagen',
          daterangerNext7Days: 'Volgende 7 dagen',
          loadingTimeline: 'Tijdlijn laden...',
          rangeInfoTotalSelectedDays: 'Totaal aantal geselecteerde dagen: ',
          rangeInfoTime: 'Tijd: ',
          rangeInfoWeekNumber: 'Weeknummer: ',
          rangeInfoMonth: 'Maand: ',
          rangeInfoTotalDays: ', Totaal aantal dagen: ',
          addTimeSlot: 'Tijdslot toevoegen...',
          slotAdded: 'Tijdslot succesvol toegevoegd.',
          changingSlot: 'Tijdslot wijzigen...',
          slotChanged: 'Tijdslot succesvol gewijzigd.',
          changingWish: 'Behoefte wijzigen...',
          wishChanged: 'Behoefte succesvol gewijzigd.',
          deletingTimeslot: 'Tijdslot verwijderen...',
          timeslotDeleted: 'Tijdslot succesvol verwijderd.',
          refreshTimeline: 'Tijdlijn vernieuwen...',
          preCompilingStortageMessage: 'Opstellen tekortbericht',
          weeklyPlanning: 'Mijn wekelijkse planning',
          weeklyPlanningOf: 'Wekelijkse planning van ',
          planning: 'Mijn planning',
          planningOf: 'Planning van ',
          minNumber: 'Minimum aantal benodigde mensen',
          time: 'Time: ',
          weekNumber: 'Weeknummer: ',
          monthNumber: 'Maand nummer: ',
          totalDays: 'Totaal dagen: ',
          removeTasksRange: function (options)
          {
            if (!_.isUndefined(options))
            {
              var html = 'Weet u zeker dat u de taken van ' + options.range.start + ' t/m ' + options.range.end;
              html += ' van ' + options.group + ' ' + options.name;
              html += ' wilt verwijderen?';
            }

            return html;
          },
          tasksDeleted: function (options)
          {
            if (!_.isUndefined(options))
            {
              var html = 'De taken van ' + options.range.start + ' t/m ' + options.range.end;
              html += ' van ' + options.group + ' ' + options.name;
              html += ' zijn verwijderd.';
            }

            return html;
          },
          noTasksFounded: 'Geen taken gevonden in de opegegeven range.',
          removeTasksTitle: 'Verwijderen taken'
        },
        message: {
          messages: 'Berichten',
          composeAMessage: 'Bericht opstellen',
          compose: 'Opstellen',
          inbox: 'Inbox',
          outbox: 'Outbox',
          trash: 'Prullenbak',
          composeMessage: 'Bericht opstellen',
          close: 'Sluiten',
          broadcast: 'Extra medium',
          sms: 'SMS',
          email: 'Email',
          receviers: 'Ontvanger(s)',
          webTRCWebLink: 'Een video conferentie is geopend doe mee! ',
          // troubled
          // chooseRecept: 'Ontvanger(s) selecteren',
          //
          subject: 'Onderwerp',
          message: 'Bericht',
          sendMessage: 'Bericht versturen',
          sender: 'Zender',
          date: 'Datum',
          questionText: 'Bericht',
          reply: 'Antwoorden',
          del: 'Verwijderen',
          noMessage: 'Er zijn geen berichten.',
          from: 'Van',
          newMsg: 'Nieuw',
          deleteSelected: 'Verwijder geselecteerde berichten',
          someMessage: 'Er zijn $v berichten',
          emptyTrash: 'Prullenbak legen',
          noMsgInTrash: 'Er zijn geen berichten.',
          box: 'Box',
          persons: 'Personen',
          restoreSelected: 'Geselecteerde berichten terugplaatsen',
          loadingMessage: 'Bericht laden...',
          escalation: 'Escalatiebericht',
          reportMessage: 'Nieuw rapport van',
          escalationBody: function (diff, startDate, startTime, endDate, endTime)
          {
            return 'Er is een tekort van ' +
              diff +
              ' mensen tussen ' +
              startDate + ' ' +
              startTime + ' en ' +
              endDate + ' ' +
              endTime + '. ' +
              'Zet uzelf a.u.b. op bereikbaar indien u bereikbaar bent voor die periode';
          },
          removed: 'Bericht succesvol verwijderd.',
          removing: 'Bericht verwijderen...',
          refreshing: 'Bericht vernieuwen...',
          removingSelected: 'Geselecteerde berichten verwijderen...',
          restoring: 'Bericht terugplaatsen...',
          restored: 'Bericht succesvol teruggeplaatst.',
          restoringSelected: 'Geselecteerde berichten terugplaatsen...',
          emptying: 'Prullenbak leegmaken...',
          emptied: 'Prullenbak succesvol geleegd.',
          sending: 'Bericht versturen...',
          sent: 'Bericht verstuurd.',
          typeSubject: 'Vul een onderwerp in.',
          // messages: 'Berichten',
          ph_filterMessage: 'Berichten filteren...',
          noReceivers: 'Selecteer een ontvanger',
          emptyMessageBody: 'Het bericht is leeg, typ a.u.b. een bericht.',
          send: 'Versturen'
        },
        groups: {
          groups: 'Groepen',
          newGroup: 'Nieuwe groep',
          newMember: 'Nieuw teamlid',
          serach: 'Zoeken',
          addNewGroup: 'Nieuwe groep toevoegen',
          editGroup: 'Groep wijzigen',
          searchResults: 'Zoekresultaten',
          group: 'Groep',
          close: 'Sluiten',
          name: 'Naam',
          saveGroup: 'Groep opslaan',
          registerMember: 'Lid registreren',
          role: 'Functie',
          selectRole: 'Selecteer een functie',
          // troubled
          // selectGroup: 'Selecteer een group',
          //
          email: 'Email',
          phone: 'Telefoon',
          address: 'Adres',
          postCode: 'Postcode',
          tel: 'Telefoonnummer',
          city: 'Woonplaats',
          userName: 'Gebruikersnaam',
          password: 'Wachtwoord',
          saveMember: 'Lid opslaan',
          serachFor: 'Zoekresultaten voor ',
          sorryCanNotFind: 'Sorry, geen resultaten.',
          addToGroup: 'Aan groep toevoegen',
          addMemberToGroup: 'Voeg geselecteerde leden aan groep toe',
          resultCount: 'Er zijn $v resultaten.',
          deleteGroup: 'Groep verwijderen',
          noMembers: 'Er zijn geen leden.',
          removeSelectedMembers: 'Geselecteerde leden verwijderen',
          memberCount: 'Er zijn $v leden.',
          searchingMembers: 'Teamleden zoeken...',
          addingNewMember: 'Nieuw lid toevoegen...',
          memberAdded: 'Lid succesvol aan groep toegevoegd.',
          refreshingGroupMember: 'Groepen- en ledenlijst vernieuwen...',
          removingMember: 'Lid uit groep verwijderen...',
          memberRemoved: 'Lid succesvol uit groep verwijderd.',
          removingSelected: 'Geselecteerde leden verwijderen...',
          saving: 'Groep opslaan...',
          groupSaved: 'Groep succesvol opgeslagen.',
          registerNew: 'Nieuw lid registreren...',
          memberRegstered: 'Lid succesvol geregistreerd.',
          deleting: 'Groep verwijderen...',
          deleted: 'Groep succesvol verwijderd.',
          filterMembers: 'Teamleden filteren...',
          searchfor: 'voornaam, achternaam..'
        },
        profile: {
          profile: 'Profiel',
          edit: 'Wijzigen',
          password: 'Wachtwoord',
          timeline: 'Tijdlijn',
          profileView: 'Profiel weergave',
          userGroups: 'Gebruikersgroepen',
          role: 'Functie',
          email: 'Email',
          phone: 'Telefoon',
          address: 'Adres',
          postcode: 'Postcode',
          city: 'Woonplaats',
          editProfile: 'Profiel wijzigen',
          name: 'Naam',
          saveProfile: 'Profiel opslaan',
          passChange: 'Wachtwoord wijzigen',
          currentPass: 'Huidig wachtwoord',
          newPass: 'Nieuw wachtwoord',
          newPassRepeat: 'Herhaal nieuw wachtwoord',
          changePass: 'Wachtwoord wijzigen',
          newAvail: 'Nieuwe bereikbaarheid',
          userName: 'Gebruikersnaam',
          pincode: 'teamlidcode',
          // saveProfile: 'Profielinformatie opslaan...',
          refreshing: 'Profielinformatie vernieuwen...',
          dataChanged: 'Profielgegevens succesvol gewijzigd.',
          savingPassword: 'Nieuw wachtwoord opslaan...',
          passwordChanged: 'Het wachtwoord is succesvol gewijzigd.',
          passwordSavedFailed: 'Er is iets mis gegaan bij het updaten van het wachtwoord.',
          pleaseFill: 'Alle velden dienen valide ingevuld te worden!',
          passNotMatch: 'Het nieuwe wachtwoord en de herhaling komen niet overeen.',
          changingPass: 'Wachtwoord wijzigen...',
          passChanged: 'Wachtwoord succesvol gewijzigd.',
          passwrong: 'Ingevoerd wachtwoord is foutief! Probeer het opnieuw.',
          currentPassWrong: 'Het ingevulde oude wachtwoord komt niet overeen met het huidige! Probeer opnieuw.',
          newTimeslotAdded: 'Nieuw tijdslot succesvol toegevoegd.',
          changingTimeslot: 'Tijdslot wijzigen...',
          timeslotChanged: 'Tijdslot succesvol gewijzigd.',
          exampleBirthDate: 'Bijvoorbeeld: 01-01-2001',
          firstName: 'Voornaam',
          lastName: 'Achternaam',
          editProfileImg: 'Profielfoto wijzigen',
          profileImgSuccessfullyUploaded: 'De profielfoto is succesvol geüpload.',
          loadUploadURL: 'Foto upload URL laden',
          click2upload: 'Klik hier om te uploaden',
          birthday: 'Geboortedatum',
          username: 'Gebruikersnaam',
          retypePassword: 'Herhaal wachtwoord',
          roleChangePrompt: 'Je verandert je eigen rol. Het systeem zal hierdoor automatisch uitloggen. Druk op "Ok" om verder te gaan.',//'You changed your own role, system will automatically logout, press "Yes" to continue.',
          specifyTeam: 'Selecteer een team voor deze gebruiker.',//'You need to sepcify a team to this user'
          authorInfo: 'Auteurinfo laden...',
          changePassWord: 'Wachtwoord wijzigen',
          safePassword: 'Wachtwoord opslaan',
          oldPassword: 'Oud wachtwoord',
          pincode: 'Teamlidcode',
          pincodeInUse: 'Deze teamlidcode is in gebruik. Kies een andere.',
          pincodeNotValid: 'Vul a.u.b. een geldige teamlidcode van maximaal 8 cijfers in!',
          pincodeCorrect: 'Deze teamlidcode is in gebruik of niet geldig! Vul a.u.b. een geldige teamlidcode.',
          pincodeInfo: 'Bovenstaande code kunt u telefonisch gebruiken om u aan te melden als TeamTelefoon uw nummer niet herkent.',
          duplicateNumber: 'Nummer bestaat al. Andere nummer invoeren aub.',
          pincodeInfoPhone: 'De laatste vier cijfers van dit telefoonnummer worden gebruikt voor de teamlidcode, tenzij deze zelf wordt opgegeven.'
        },
        settings: {
          settings: 'Instellingen',
          user: 'Gebruiker',
          application: 'Applicatie',
          userSettings: 'Gebruikersinstellingen',
          appSettings: 'Applicatie-instellingen',
          saveSettings: 'Instellingen opslaan',
          langSetting: 'Taal',
          saving: 'Instellingen wijzigen...',
          refreshing: 'Instellingen vernieuwen...',
          saved: 'Instellingen succesvol gewijzigd.'
        },
        help: {
          header: 'Hulp & Ondersteuning',
          support: 'Ondersteuning',
          teamTelephone: {
            setReachabilityPhone: 'Hoe geef ik telefonisch mijn bereikbaarheid door?',
            setReachabilityWeb: 'Hoe wijzig ik mijn bereikbaarheid in de web applicatie?',
            changeReachabilityTeamMember: 'Hoe wijzig ik de bereikbaarheid van een teamlid?',
            changeCallOrderTeam: 'Hoe wijzig ik de belvolgorde van mijn team?',
            changeCallOptions: 'Hoe wijzig ik de belinstellingen van mijn team?'
          },
          teams: {
            addNewMember: 'Hoe voeg ik een nieuw lid toe aan mijn team?',
            addExistingMember: 'Hoe voeg ik een bestaand lid toe aan mijn team?',
            removeMember: 'Hoe verwijder ik een lid uit mijn team?'
          },
          web: {
            title: 'Web applicatie',
            newMember: 'Hoe kan ik een nieuwe patiënt te creëren?'
          },
          manuelTeamTelephone: {
            title: 'Handleiding TeamTelefoon',
            download: 'Handleiding downloaden',
          },
          android: {
            title: 'Android',
            addClientReport: 'Hoe voeg ik een cliënt rapport toe?',
            callClient: 'Hoe werkt het als ik een cliënt wil bellen',
          }
        },
        downloads: {
          app: 'Binnenkort te downloaden.',
          manual: 'Download handleiding'
        },
        loading: {
          general: 'Laden',
          manage: 'beheren',
          dashboard: 'dashboard',
          planboard: 'agenda',
          messages: 'berichten',
          teams: 'teams',
          profile: 'profiel',
          settings: 'instellingen'
        },
        teamup: {
          teams: 'Teams',
          selectTeam: 'Selecteer team',
          hour: 'uur',
          clients: 'Cliënten',
          order: 'Volgorde',
          logs: 'Logs',
          options: 'Instellingen',
          selectClientGroup: 'Selecteer een cliëntgroep',
          loadMembersByName: 'Leden laden...',
          loadingMembers: 'Leden zoeken...',
          howToSearchMembers: 'Zoek leden bij voor- en/of achternaam.',
          selectClientGroup: 'Selecteer een cliëntgroep',
          manage: 'Beheren',
          teamTelephone: 'Team-telefoon',
          chooseTeam: 'Selecteer een team',
          undefinedTeamMember: 'Onbekend teamlid',
          defaultTeam: 'Standaard team',
          edit: 'Bewerk',
          editTeam: 'Bewerk team',
          team: 'Team',
          del: 'Verwijder',
          noMembers: 'Geen leden in dit team.',
          newTeam: 'Nieuw Team',
          teamName: 'Teamnaam',
          createTeam: 'Opslaan',
          newMember: 'Nieuw teamlid',
          noMembersFound: 'Geen leden gevonden met de opgegeven zoekterm.',
          name: 'Naam',
          role: 'Rol',
          phone: 'Telefoon',
          street: 'Straat',
          postCode: 'Postcode',
          city: 'Woonplaats',
          email: 'E-mail',
          saveMember: 'Opslaan',
          state: 'Status',
          states: 'Status',
          saveTeam: 'Team opslaan',
          save: 'Opslaan',
          refreshing: 'Teaminformatie opnieuw ophalen',
          dataChanged: 'Data is veranderd.',
          teamSubmitError: 'Fouten tijdens het aanmaken: ',
          queryTeamError: 'Fouten tijdens het opzoeken van de teams.',
          teamNamePrompt1: 'Vul een teamnaam in.',
          teamNamePrompt2: 'Voeg contactdata toe a.u.b.',
          cancel: 'Annuleren',
          chooseRole: 'Kies een rol',
          func: 'Functie',
          chooseFunction: 'Kies een functie',
          newClientGroup: 'Nieuwe groep',
          newClient: 'Nieuwe cliënt',
          reports: 'Rapporten',
          report: 'Rapport',
          noClients: 'Geen cliënten in deze groep',
          noClientGroup: 'Geen clientgroep',
          TeamClients: 'TEAMS - CLIËNTEN',
          createClientGroup: 'Opslaan',
          contacts: 'Contacten',
          Number: 'Nummer',
          clientProfileUrl: 'URL Cliëntenprofiel',
          addContact: 'Contactpersoon toevoegen',
          editContact: 'Contactpersoon wijzigen',
          saveClient: 'Opslaan',
          group: 'Groep',
          errorSaveClientGroup: 'Opslaan wijzigingen cliëntengroep mislukt.',
          noContacts: 'Er zijn geen contactpersonen gedefinieerd.',
          noReports: 'Er zijn geen rapporten voor deze cliënt.',
          contactCount: 'Er zijn $v contactpersonen.',
          reportCount: 'Er zijn $v rapporten.',
          accountInfoFill: 'Vul uw accountinformatie in a.u.b.',
          passNotSame: 'Wachtwoorden zijn niet hetzelfde.',
          savingMember: 'Lid aan het opslaan...',
          selectTeam: 'Selecteer een team',
          clinetInfoFill: 'Vul de cliëntinformatie (naam en telefoon) in a.u.b.',
          savingClient: 'Cliënt aan het opslaan...',
          clientSubmitError: 'Fouten bij het aanmaken van een nieuwe cliënt.',
          clientGroups: 'Cliëntengroepen',
          saveClientGroup: 'Opslaan cliëntgroep...',
          deleteClientFromClientGroup: 'Cliënt is verwijderd',
          deletingClientFromClientGroup: 'Cliënt uit groep verwijderen...',
          teams_Cap: 'Teams',
          noTeamNameFound: 'Teamnaam onbekend',
          noTeam: 'Geen team',
          searchMembers: 'Zoek leden...',
          editClient: 'Bewerk cliënt',
          loadingNumber: 'Teamtelefoonnummer aan het laden...',
          loadClients: 'Cliënten laden...',
          birthdayError: 'Fout in de geboortedatum.',
          map: 'kaart',
          saveContacts: 'Contactpersonen opslaan',
          loadingReports: 'Rapporten laden',
          reportEmpty: 'Voer een valide titel en beschrijving in!',
          reportValid: 'De invoervelden zijn niet valide!',
          reportBody: 'Beschrijving',
          reportBodyRequired: 'Vul een beschrijving in!',
          reportTitleRequired: 'Vul een titel in!',
          reportBodyMinChars: 'De beschrijving moet uit minimaal 8 karakters bestaan!',
          reportTitleMinChars: 'De beschrijving moet uit minimaal 4 karakters bestaan!',
          reportBodyMaxChars: 'De beschrijving mag maximaal 150 karakters bestaan!',
          reportTitleMaxChars: 'De titel kan uit maximaal 30 karakters bestaan!',
          checkLocalStorage: 'In deze webbrowser is de privé-modus ingeschakeld. Dit wordt niet ondersteund. Hier vindt u informatie over hoe u de privé-modus kunt uitschakelen:',
          readMore: 'Lees meer',
          date: 'Datum',
          datetime: 'Datum en tijd',
          writenBy: 'Geschreven door',
          noSharedStates: 'Geen gedeelde status',
          savingContacts: 'Contactpersonen oplsaan',
          // delClientGroupConfirm: 'Weet u zeker dat u deze cliëntengroep wilt verwijderen? Het kan even duren.',
          // delTeamConfirm: 'Weet u zeker dat u dit team wilt verwijderen? Het kan even duren.',
          deletingClientGroup: 'Groep verwijderen... ',
          from: 'Van',
          to: 'Tot',
          time: 'Tijd',
          duration: 'Duur',
          coordinatorNoTeam: 'Het lijkt erop dat je niet in een team zit. Wijs jezelf toe aan een team.',
          teamMemberNoTeam: 'Het lijkt erop dat je niet in een team zit. Neem contact op met een coordinator.',
          //deleteConfirm: 'Druk op OK om door te gaan.',
          confirms: {
            deleteClientTitle: 'Verwijder client',
            deleteClient: 'Weet u zeker dat u de client wilt verwijderen?',
            deleteClientFromTeamTitle: 'Verwijder client uit de groep',
            deleteClientFromTeam: 'Weet u zeker dat u de client uit zijn groep wilt verwijderen?',
            deleteReportTitle: 'Verwijder rapport',
            deleteReport: 'Weet u zeker dat u het rapport wilt verwijderen?',
            deleteProfileTitle: 'Verwijder profile',
            deleteProfile: 'Weet u zeker dat u het profiel wilt verwijderen?',
            deleteMemberFromTeamTitle: 'Verwijder het lid uit alle teams',
            deleteMemberFromTeam: 'Weet u zeker dat u het lid uit alle teams wilt verwijderen? Let op: iemand die niet in een team zit, kan TeamUp niet gebruiken. ',
            deleteMemberTitle: 'Verwijderen teamlid',
            deleteMember: 'Weet u zeker dat u het teamlid van het team wil verwijderen?',
            deleteClientGroupTitle: 'Verwijder cliëntengroep',
            deleteClientGroup: 'Weet u zeker dat u deze cliëntengroep wilt verwijderen? Het kan even duren.',
            deleteTeamTitle: 'Verwijderen team',
            deleteTeam: 'Weet u zeker dat u dit team wilt verwijderen? Het kan even duren.',
            deleteTaskTitle: 'Verwijderen taak',
            deleteTask: 'Weet u zeker dat u de taak wilt verwijderen?',
            deleteContactTitle: 'Verwijder contact',
            deleteContact: 'Weet u zeker dat u het contact wilt verwijderen?',
            remove: 'Verwijderen',
            addTeamMemberCodeAsPhoneTitle: 'Teamlidcode wijzigen',
            addTeamMemberCodeAsPhone: 'Er is een eigen teamlidcode ingevoerd, die niet overeen komt met de laatste vier cijfers van uw standaard telefoonnummer?',
            photoRemoveTitle: 'Profielfoto verwijderen',
            photoRemoveBody: 'Weet u zeker dat u de profielfoto wilt verwijderen?',
            yes: 'Ja, dat wil ik',
            no: 'Nee, annuleren',
            cancel: 'Annuleren',
            day: {
              sunday: 'zondag',
              monday: 'maandag',
              tuesday: 'donderdag',
              wednesday: 'woensdag',
              thursday: 'donderdag',
              friday: 'vrijdag',
              saturday: 'zaterdag'
            },
            shortDay: {
              su: "zo",
              mo: "ma",
              tu: "di",
              we: "wo",
              th: "do",
              fr: "vr",
              su: "za"
            }
          },
          deletingTeam: 'Team verwijderen...',
          deletingMember: 'Lid verwijderen ...',
          deletingClient: 'Cliënt verwijderen ...',
          noMessages: 'Er zijn geen berichten.',
          newReport: 'Nieuw rapport',
          editReport: 'Wijzig rapport',
          selectClient: 'Selecteer een cliënt',
          selectMember: 'Selecteer een lid',
          selectMonth: 'Selecteer een maand',
          saveReport: 'Rapport opslaan',
          reportTitle: 'Titel',
          selectSlot: 'Selecteer een periode',
          editClientImg: 'Wijzig foto van de cliënt',
          newTask: 'Nieuwe taak',
          updateTask: 'Wijzig taak',
          managePanelchangePrompt: 'Data is gewijzigd. Klik op \'Ok\' om door te gaan, \'Annuleren\' om te blijven.',
          pagePrevious: 'Vorige',
          pageNext: 'Volgende',
          pageFirst: 'Eerste',
          pageLast: 'Laatste',
          refresh: 'Verversen',
          stateValue: {
            'reachable': 'Bereikbaar',
            'available': 'Beschikbaar',
            'working': 'Aan het werk',
            'offline': 'Offline',
            'not_reachable': 'Niet bereikbaar',
            'on_the_phone': 'Aan de telefoon',
            'unknown': 'Onbekend',
            'reachable': 'Bereikbaar',
            'possibly_reachable': 'Niet gepland',
            'unreachable': 'Niet bereikbaar',
            'unavailable': 'Niet beschikbaar',
            'unknown': 'Offline'
          },
          reportNotExists: 'Rapport bestaat niet.',
          sessionTimeout: 'Uw sessie is verlopen. Graag nogmaals inloggen.',
          errorCode: {
            '1': 'Onbekende foutmelding',
            '2': 'De Deomeinagent is niet gevonden. Opnieuw inloggen zou dit probleem op kunnen lossen.',
            '3': 'Dit lid moet de rol van coördinator hebben, voordat er een team aangemaakt kan worden',
            '4': 'Eeen agent id mag alleen uit alpha nummerieke karakters, onder- en streepjes bestaan',
            '5': 'Kan de JSON niet parsen of de JSON body',
            '6': 'Een of meerdere paramters zijn er niet',
            '7': 'De group "members" is niet gevonden',
            '8': 'Team met het gegeven teamUuid bestaat niet',
            '9': 'Dit lid maakt geen deel uit van het team',
            '10': 'Team met het gegeven teamUuid bestaat niet',
            '11': 'Dit lid moet de rol van coördinator hebben, voordat er een nieuw team aangemaakt kan worden',
            '12': 'De team agent kon niet aangemaakt worden',
            '13': 'De uuid parameter en het uuid in de payload komen niet overheen',
            '14': 'Een lid met dit uuid bestaat al',
            '15': 'Een van de meegstuurde waardes is onbekend',
            '16': 'Een van de volgende settings heeft als waarde null, Dit is niet mogelijk',
            '17': 'Een van de meegestuurde waardes heeft een onbekend type',
            '18': 'De gebruiker met het opgegeven id bestaat niet',
            '19': 'Het ingevoerde oude wachtwoord komt niet overheen met het huidige',
            '20': 'Dit lid moet de rol van coördinator hebben, voordat er een wachtwoord van een ander lid gewijzigd kan worden',
            '21': 'Een parameter kan niet geparst worden',
            '22': 'Dit lid is in geen enkel team'
          }
        },
        options: {
          title: 'Instellingen',
          smsMissedCall: 'SMS bij een gemist gesprek of nieuwe voicemail',
          receiveReachableMembers: 'Bereikbare teamleden ontvangen',
          missedOrVoicemail: 'SMS als het team een gesprek heeft gemist of als er een voicemail is ingesproken',
          hasSms: function (sms)
          {
            return (sms)
              ? 'een'
              : 'geen';
          },
          on: 'Aan',
          off: 'Uit',
          ringingTimeOut: {
            title: 'Rinkeltijd',
            short: 'Bij een langere rinkeltijd hebben teamleden meer tijd om op te nemen, maar de totale wachttijd voor cliënten kan langer zijn als er veel teamleden zijn aangemeld.',
            long: 'Bij een rinkeltijd van meer dan 15 seconden is het aanbevolen dat alle teamleden hun persoonlijke voicemail uitschakelen.',
          },
          personalVoicemailPrevention: 'Persoonlijke voicemailpreventie',
          personalVoicemailPreventionInfo: 'Als deze optie is ingeschakeld, krijgen teamleden eerst de vraag of ze het gesprek willen aannemen van een cli&euml;nt. Door deze optie aan te zetten, kan worden voorkomen dat een cli&euml;nt wordt doorverbonden met de persoonlijke voicemail van een teamlid.',
          voicemailDetectionInfo: 'Bij een rinkeltijd van meer dan 15 seconden is het aanbevolen dat alle teamleden hun persoonlijke voicemail uitschakelen of om gebruik te maken van de persoonlijke voicemailpreventie. Het uitzetten van de persoonlijke voicemail (van de werktelefoon) kunt u regelen bij de telefoonprovider.'
        },
        task: {
          information: 'Informatie',
          noTasks: 'Geen taken',
          clientName: 'Cliënt',
          memberName: 'Lid',
          orderType1: 'Standaard volgorde',
          orderType2: 'Tijd',
          tasks: 'Taken',
          myTask: 'Mijn taken',
          newTask: 'Nieuwe Taak',
          orderby: 'Sorteer op',
          allTasks: 'Alle taken',
          description: 'Opmerkingen',
          filltheTime: 'Vul de start- en eindtijd in voor de taak.',
          startTimeEmpty: 'Vul de startdatum en -tijd in.',
          endTimeEmpty: 'Vul de einddatum en -tijd in.',
          planTaskInFuture: 'U kunt geen taak in het verleden aanmaken. Selecteer een start- en eindtijd in de toekomst.',
          startLaterThanEnd: 'Beginttijd moet eerder zijn dan de eindtijd.',
          specifyClient: 'Selecteer een cliënt voor deze taak.',
          creatingTask: 'Taak wordt aangemaakt',
          editingTask: 'Taak wordt gewijzigd',
          taskSaved: 'Taak is opgeslagen.',
          deleteTaskConfirm: 'Weet u zeker dat u deze taak permanent wilt verwijderen?',
          taskDeleted: 'Taak verwijderd.',
          planningTime: 'Tijdsbestek',
          refreshTask: 'Het herladen van de taken',
          upload: 'Upload taken',
          deleteTasksConfirm: 'Weet u zeker dat u deze taken permanent wilt verwijderen?',
          taskDescriptionMinChars: 'Opmerkingen moeten uit minimaal 8 karakters bestaan.',
          taskDescriptionMaxChars: 'Het maximaal aantal karakters voor opmerkingen is 500.',
          taskFormValide: 'De nieuwe taak is niet valide! Ga de eisen onder elk veld na.'
        },
        order: {
          randomOrder: 'Willekeurige',
          fixedOrder: 'Eigen volgorde',
          confirmation: 'Bevestig Keuze',
          randomFeedback: 'Een willekeurige volgorde wordt bepaald.',
          loadTeam: 'Team laden...',
          orderSaved: 'Volgorde opgeslagen',
          noMembers: 'Er zijn geen leden in dit team.'
        },
        logs: {
          loadLogs: 'Logs laden...',
          empty: 'Er zijn geen logs',
          filter: 'Filter logs...',
          status: {
            sent: 'Uitgaand',
            received: 'Inkomend',
            finished: 'Afgerond',
            missed: 'Gemist',
            delivered: 'Ontvangen',
            error: 'Fout'
          }
        },
        validation: {
          phone: {
            notValid: 'Voer een valide telefoonnummer in!',
            invalidCountry: 'Landcode incorrect! Alleen Nederlandse (+31) nummers toegestaan.',
            tooShort: ' (Telefoonnummer niet correct: te weining nummers.)',
            tooLong: ' (Telefoonnummer niet correct: teveel cijfers.)',
            notValidOnSubmit: 'Vul alstublieft minimaal een geldig telefoonnummer in om op te slaan.',
            message: 'Ingevoerd telefoonnummer is correct. Nummer is geregistreerd in ',
            as: ' als ',
            multipleNotvalid: 'Een of meerdere telefoonnummers zijn niet valide!',
            fixedLine: 'een vast nummer',
            mobile: 'een mobiel nummer',
            mobileOrFixedLine: 'een vast of mobielnummer'
          },
          pincode: {
            exists: 'Kiest u a.u.b. een andere teamlidcode. Deze is in gebruik!'
          },
          password: {
            amountMinChars: function (chars)
            {
              return ' en dient uit minimaal ' + chars + ' teken(s) te bestaan'
            },
            amountMaxChars: function (chars)
            {
              return ' en mag uit maximaal ' + chars + ' tekens(s) te bestaan'
            },
            oldPassMatch: 'Het ingevulde oude wachtwoord komt niet overheen met het huidige.',
            required: 'Een wachtwoord is verplicht'
          },
          email: {
            notValid: 'Voer een valide e-mailadres in!',
            required: 'Een e-mail is verplicht'
          },
          role: 'Kies een rol!',
          birthDate: {
            notValid: 'Voer een valide geboortedatum in!'
          },
          userName: {
            regex: 'De gebruikersnaam mag alleen uit alphanummerieke tekens bestaan, inclusief streepjes en onderstreepjes',
            valid: 'Een gebruikersnaam is vereist'
          },
          search: {
            notValid: 'Voer een voor en/of achternaam in!'
          }
        }
      }
    }
  }
);
